- stubs/app/Models/Team.php
Had to do a double take on this one. 😄   Suggests that fillable attributes _are_ mass assignable.
> Fillable Comment Fix

- src/Console/InstallCommand.php
Since the package updates the "home" route, I think we should also update the link on the welcome page.
I know that this page is not really used in real applications but I think it would be nice to have a working link.
> Replace the "home" route by the "dashboard" route

- stubs/inertia/resources/js/Pages/Profile/UpdatePasswordForm.vue
- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
- stubs/livewire/resources/views/profile/update-password-form.blade.php
- stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
- stubs/resources/views/auth/login.blade.php
- stubs/resources/views/auth/register.blade.php
- stubs/resources/views/auth/reset-password.blade.php
- stubs/resources/views/auth/two-factor-challenge.blade.php
This pull request adds an autocomplete attribute on all relevant elements to better comply with the HTML standard and improve user experience through improved browser autocomplete detection.
> Include autocomplete on all relevant elements.

- database/migrations/2014_10_12_000000_create_users_table.php
- database/migrations/2020_05_21_100000_create_teams_table.php
- database/migrations/2020_05_21_200000_create_team_user_table.php
- src/Console/InstallCommand.php
- src/HasTeams.php
- src/Http/Controllers/Inertia/TeamMemberController.php
- src/Http/Livewire/TeamMemberManager.php
- src/Jetstream.php
- stubs/app/Models/User.php
- stubs/app/Models/UserWithTeams.php
- tests/Fixtures/User.php
Use numeric IDs for users since using UUIDs for the authenticatable model would break many packages in the Laravel ecosystem.
> use numeric ids for users

- tests/DeleteUserWithTeamsTest.php
- tests/UpdateTeamTest.php
- Using the `assertSame` to replace `assertEquals` to make assertion equals checking strict.
> Using assertSame to make assert equals strict

- src/Http/Middleware/ShareInertiaData.php
This allows using Inertia for unauthenticated routes. I ran into this when moving the authentication scaffolding to Inertia, which I'll admit is outside the intended scope of the package, but still would be nice to have it working.
<details>
<summary>For anyone else running into this while this is open (or rejected), here's a hacky workaround</summary>
Add this function at the end of your `app/Http/Kernel.php`:
```php
public function updateWebGroup(\Closure $closure)
{
$this->middlewareGroups['web'] = $closure($this->middlewareGroups['web']) ?? $this->middlewareGroups['web'];
$this->syncMiddlewareToRouter();
}
```
And this to the boot method of your `JetstreamServiceProvider`:
```php
$this->app->make(Kernel::class)->updateWebGroup(function (array $web) { …
```
> Allow using Inertia without a session

- src/Actions/RemoveTeamMember.php
One of the error messages - when removing team member - cannot be translated.
> Make error message translatable

- stubs/inertia/resources/views/app.blade.php
- stubs/livewire/resources/views/layouts/app.blade.php
- stubs/resources/views/layouts/guest.blade.php
This PR sets the language attribute on the HTML tag of both stacks to follow the application's configured locale, like the welcome view does.
See #56
> Use application language on layouts

- stubs/resources/views/auth/forgot-password.blade.php
- stubs/resources/views/auth/login.blade.php
- stubs/resources/views/auth/register.blade.php
- stubs/resources/views/auth/reset-password.blade.php
- stubs/resources/views/auth/two-factor-challenge.blade.php
- stubs/resources/views/auth/verify-email.blade.php
Add helper `__(` to auth views
> refactor: make auth views translatables

- stubs/app/Models/Team.php
App\Models\Team extends Laravel\Jetstream\Team and it dont need import Illuminate\Database\Eloquent\Model
> refactor: remove unused import

- stubs/inertia/resources/js/Pages/Teams/DeleteTeamForm.vue
- stubs/livewire/resources/views/teams/delete-team-form.blade.php
Fixes a spelling issue in the DeleteTeamForm component. 
Changes:
1. "Once a team is deleted, all of its resources and data will be permanently deleted. Before deleting this team, please download any data or information **regrading** this team that you wish to retain." 
to:
1. "Once a team is deleted, all of its resources and data will be permanently deleted. Before deleting this team, please download any data or information **regarding** this team that you wish to retain."
> Typo: DeleteTeamForm component confirmation modal

- src/Jetstream.php
- src/JetstreamServiceProvider.php
This PR introduces a way of disabling registration of the default routes like other Laravel packages already allow (Cashier, for example). It also adds an option to publish the routes for the adapter you're currently using to your routes folder.
Resubmission of #54
> Provide a way of customizing/disabling the default routes

- src/HasTeams.php
- tests/TeamBehaviorTest.php
Resolves #62 by checking whether authenticated user is utilising a Sanctum access token prior to comparing token and team permissions.
Enhanced tests to include scenario for web-based user and authenticated user. Updated token test to utilise Sanctum mock to compare explicit API permission matching to team permissions.
> Fix API vs Web TeamsHasPermissions, add Tests

- stubs/resources/views/auth/login.blade.php
The "remember me" checkbox does not specify an attribute of `name="remember"`, so the cookie isn't actually being set.
> Fix "remember me" checkbox

- resources/views/components/welcome.blade.php
This PR addresses an issue where the left hand edge of the welcome page boxes don't align with the content above it. Before this PR, the welcome page looks like this:
And afterwards, it looks like this:
Everything has a little bit more breathing room and the edges now align perfectly :smile:
**NOTE:** I'm not sure if I'm supposed to compile the assets for this as the `p-8` class is stripped (I assume by PurgeCSS) but I can't see any way of generating them easily for this PR. If there's another step I need to take, please let me know so that I can do it 😄
> Fix alignment of the welcome page.

- src/Console/InstallCommand.php
On windows, the Services Providers was not added to the app.php file.
After some tests I realized that it would be enough to remove the PHP_EOL tag.
> Fix InstallCommand.php

- src/Http/Middleware/ShareInertiaData.php
- stubs/app/Actions/Jetstream/CreateTeam.php
- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/livewire/resources/views/layouts/app.blade.php
- tests/CreateTeamTest.php
- tests/CurrentTeamControllerTest.php
- tests/DeleteUserWithTeamsTest.php
- tests/TeamBehaviorTest.php
Would be useful to automate using the `TeamPolicy`, as for Inertia.js mostly referring to https://inertiajs.com/security#authorization as reference.
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> Implement TeamPolicy::create authorization check before creating a team.

- src/Http/Controllers/Inertia/CurrentUserController.php
- src/Http/Livewire/DeleteUserForm.php
- stubs/inertia/resources/js/Pages/Profile/DeleteUserForm.vue
- stubs/livewire/resources/views/profile/delete-user-form.blade.php
Introduces password confirmation for user deletion on Livewire and Inertia
> Delete User password confirmation

- src/JetstreamServiceProvider.php
Add missing file extension when publishing jetstream routes
> Add missing extension when publishing routes

- README.md
- composer.json
- src/Http/Controllers/Inertia/UserProfileController.php
- src/JetstreamServiceProvider.php
The session table name is currently hardcoded in UserProfileController's session function, this change updates the function to use the table name configured in session.php
> Updating session function to use configured table

- src/JetstreamServiceProvider.php
When publishing routes for jetstream, it copy routes file to "routes/jetstream" without .php extension.
> Fix for vendor:publish routes

- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
- stubs/inertia/resources/js/Pages/Teams/CreateTeamForm.vue
- stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
- stubs/inertia/resources/js/Pages/Teams/UpdateTeamNameForm.vue
- stubs/livewire/resources/views/layouts/app.blade.php
- stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
- stubs/livewire/resources/views/teams/create-team-form.blade.php
- stubs/livewire/resources/views/teams/team-member-manager.blade.php
- stubs/livewire/resources/views/teams/update-team-name-form.blade.php
Added the user's name to every image alt attribute.
You cannot navigate to profile through the UI anymore if the image becomes broken, it simply disappears. As well as alt tags should be set.
Its currently just the users name property, should we add `USERNAME's Profile Picture` to make it more descriptive for a11y? Or since the image is actually used to navigate to the profile maybe even `Open Dropdown`?
> Add alt attribute/value to image tag

- resources/views/components/switchable-team.blade.php
If you make use of an to long team name the text "overflows" the box.
eg:
This PR would fix that by adding "truncate" class to the menu entry:
> Make team menu entry "truncate" (text-overflow)

- src/Jetstream.php
Keeping some parody with the way the User model is managed by the Jetstream service, the Team and Membership models are now treated the same way.
This was inspired by #118 since that made me realize editing models location wouldn't be done in a consistent manner. So if all you wanted to do was point models to a different location you'd be overriding properties and methods. So by exposing all as static properties, now you only would add properties to your extension of Jetstream.
---
```
<?php
namespace App;
use App\SomeOther\Folder\User;
class MyJetstream extends \Laravel\Jetstream\Jetstream
{
public static $userModel = User::class;
/**
* Get the name of the team model used by the application.
*
* @return string
*/
public static function teamModel()
{
return 'App\\SomeOther\\Folder\\Team'; …
```
> Use static properties for Team and Membership too

- src/Jetstream.php
Per title this is a follow up to #119 to add the equivalent use*Model methods to configure without extending the Jetstream class.
> Add useTeamModel and useMembershipModel to compliment useUserModel

- stubs/livewire/resources/views/api/api-token-manager.blade.php
- stubs/livewire/resources/views/api/index.blade.php
- stubs/livewire/resources/views/dashboard.blade.php
- stubs/livewire/resources/views/layouts/app.blade.php
- stubs/livewire/resources/views/profile/delete-user-form.blade.php
- stubs/livewire/resources/views/profile/logout-other-browser-sessions-form.blade.php
- stubs/livewire/resources/views/profile/show.blade.php
- stubs/livewire/resources/views/profile/two-factor-authentication-form.blade.php
- stubs/livewire/resources/views/profile/update-password-form.blade.php
- stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
- stubs/livewire/resources/views/teams/create-team-form.blade.php
- stubs/livewire/resources/views/teams/create.blade.php
- stubs/livewire/resources/views/teams/delete-team-form.blade.php
- stubs/livewire/resources/views/teams/show.blade.php
- stubs/livewire/resources/views/teams/team-member-manager.blade.php
- stubs/livewire/resources/views/teams/update-team-name-form.blade.php
The pull request is to add to the livewire configuration the option that labels have multi-language capacity, in order to facilitate internationalization with applications that are developed in other countries.
Example
**Before**
Permanently delete your account.
**After**
{{ __('Permanently delete your account.') }}
> add support multilang to livewire

- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
- stubs/livewire/resources/views/layouts/app.blade.php
- stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
Adding object-cover to all places that display user avatar. This fixes distorted avatars when users are using tall aspect-ratio image.
> Added object-cover to profile images

- src/Http/Middleware/ShareInertiaData.php
The authorize call in ShareInertiaData causes an AuthorizationException, this means the data is not shared with Inertia. Changing authorize to check returns the boolean value and will populate canCreateTeams correctly when TeamPolicy->create returns false.
This closes #113
> [1.x] Inertia: Use check instead of authorize for canCreateTeams

- src/Http/Controllers/Inertia/ApiTokenController.php
- src/Http/Livewire/ApiTokenManager.php
- stubs/app/Actions/Jetstream/AddTeamMember.php
- stubs/app/Actions/Jetstream/CreateTeam.php
- stubs/app/Actions/Jetstream/UpdateTeamName.php
Jetstream broadly uses the array-syntax for validation rules, which makes them a little easier to work with than their pipe-delimited cousins.
I've updated the places in both the main package and stubs to consistently use the array-syntax.
> Consistently use array-syntax for validation rules

- src/Http/Livewire/ApiTokenManager.php
Fixes #152 
* When a user views the permissions modal for an API Token, a property on the component called `$managingPermissionsFor` is set to the corresponding API Token model
* If a user clicks "delete" and the model is no longer in the Database, that property hasn't been "unset", so when livewire goes to look it up by ID, it can't find it and a 404 error is thrown.
* Immediately after deleting an API Token model, unset the `$managingPermissionsFor` property
> [1.x] Fix API token deletion bug

- stubs/inertia/resources/js/Pages/Teams/CreateTeamForm.vue
- stubs/inertia/resources/js/Pages/Teams/UpdateTeamNameForm.vue
- stubs/livewire/resources/views/teams/create-team-form.blade.php
- stubs/livewire/resources/views/teams/update-team-name-form.blade.php
I realised profile pictures of team owners are missing  `object-cover` class so it looks distorted if the picture uploaded is not a square.
> Fix profile picture distortion for team owners

- stubs/app/Actions/Fortify/CreateNewUser.php
- stubs/app/Actions/Fortify/CreateNewUserWithTeams.php
This PR address issue: https://github.com/laravel/jetstream/issues/167
Currently the Fortify Action Stubs aren't in sync with this repo so this is an attempt to update them so when users install jetstream they are fully to to date with Fortify's stub.
> Update Fortify Actions CreateNewUser.php and CreateNewUserWithTeams.php stubs to use PasswordValidationRules Trait

- src/HasTeams.php
When adding with('currentTeam') to an eloquent builder an error happens:
The issue is because the `currentTeam` method is checking if the user has `current_team_id` in order to set the default current_team_id based on the personal team. However, since the builder isn't a user itself, it always tries to perform this action.
Adding the check to see if the id is there, we will make sure that is a single user and not a query.
> Fix HasTeams trait to be able to use queries with('currentTeam')

- stubs/livewire/resources/views/api/api-token-manager.blade.php
- stubs/livewire/resources/views/profile/update-password-form.blade.php
- stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
- stubs/livewire/resources/views/teams/create-team-form.blade.php
- stubs/livewire/resources/views/teams/team-member-manager.blade.php
- stubs/livewire/resources/views/teams/update-team-name-form.blade.php
I found out I could not translate my livewire labels in Jetstream a few minutes ago, so I figured out I wanted to contribute with a little PR to help others in addition to the future myself.
> [1.x] Make labels translatable in livewire views

- .styleci.yml
- stubs/app/Models/User.php
The stub for the User model is missing the `Illuminate\Contracts\Auth\MustVerifyEmail` interface which is in the default [Laravel project](https://github.com/laravel/laravel/blob/master/app/Models/User.php#L5) and mentioned in the [Jetstream docs](https://jetstream.laravel.com/1.x/features/authentication.html#email-verification) as already being present.
> [1.x] Add MustVerifyEmail Interface to User Model

- resources/views/components/confirms-password.blade.php
- src/ConfirmsPasswords.php
- src/Http/Livewire/TwoFactorAuthenticationForm.php
- src/Http/Middleware/ShareInertiaData.php
- src/JetstreamServiceProvider.php
- stubs/inertia/resources/js/Jetstream/ConfirmsPassword.vue
- stubs/inertia/resources/js/Pages/Profile/TwoFactorAuthenticationForm.vue
- stubs/livewire/resources/views/profile/two-factor-authentication-form.blade.php
This adds a new `confirms-password` component for both Livewire and Inertia/Vue for quickly placing a password confirmation prompt around a given action.
> Confirmable Support

- stubs/livewire/resources/views/profile/show.blade.php
If the updatePasswords feature is disabled (because the project is implementing password-less login) then the password form should be excluded from the profile view
> Don't include update password form if feature disabled (livewire)

- routes/inertia.php
- src/HasProfilePhoto.php
- src/Http/Controllers/Inertia/CurrentUserController.php
- src/Http/Livewire/UpdateProfileInformationForm.php
- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
- stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
Add a button next to "Select a new Photo" that will have the function of delete the current photo and return to the Jetstream default profile photo.
This can be good if an user want to remove your photo temporarily or if the person want to use the default jetstream photo.
A more interesting case would be if the site had been modified the jetstream to use Gravatar and the user want to use he/she Gravatar profile photo.
> [1.x] Add delete profile photo button

- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
- stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
Just a button fix of the remove photo button position on small screens. This update does not change anything visually for desktop screens. 
How is being displayed now:
How it will be shown:
> Fix button margins on small screens

- stubs/inertia/resources/views/app.blade.php
- stubs/livewire/resources/views/layouts/app.blade.php
```html
<link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('css/app.css') }}">
```
I fixed the inconsistent ordering of the `rel` attribute. I like keeping the code consistent and found it a bit annoying or tedious having to manually re-organize them after starting a new Laravel 8 project.
> Fixed attribute order inside views

- resources/views/components/modal.blade.php
This change ensures that the modal dialog is always on the front.
> [1.x] Update modal z-index

- stubs/livewire/resources/views/profile/delete-user-form.blade.php
- stubs/livewire/resources/views/profile/logout-other-browser-sessions-form.blade.php
- stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
> [1.x] Add translate __(' ') notation to some jetstream components

- stubs/inertia/resources/views/app.blade.php
The current use of asset() makes a freshly installed JetStream application incompatible with Laravel mix hot-reload.
> [1.x] Use mix() instead of asset() for hot-reload support

- resources/views/components/switchable-team.blade.php
- stubs/livewire/resources/views/navigation-dropdown.blade.php
Only for Livewire, I don't use Vue so cannot test if these changes would work in the vue component.
Ensures the correct endpoints are rendered in the html should the underlying route definition change
> [1.x] Remove Hard Coded Livewire Routes

- stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
Corrects the ID value for the email field which was incorrect causing the email label not to be linked to the field and a console warning that two elements on the page had the ID "name".
> Correct ID value for email field

- stubs/inertia/tailwind.config.js
- stubs/livewire/tailwind.config.js
If you do not publish the Jetstream views, those CSS classes will be purged from Tailwind on production builds, resulting in broken layouts.
**Example:**
This PR fixes this issue **and** allows the Jetstream views to remain unpublished by simply including Jetstream in the list of folder PostCSS needs to search for classes.
**Result:**
Keeping, non-customized, views unpublished is what I prefer because it keeps my repository clean and I only publish files I actually need to modify.
---
Really fixes: https://github.com/laravel/jetstream/issues/170
> [1.x] Fix purging of CSS classes on production builds

- src/HasTeams.php
- tests/AddTeamMemberTest.php
I have added this check because we do have a `hasTeamPermission` function but I missed a function to check if the team has a specific role.
When I checked the trait I saw the following function `teamRole` which returns the role object.
So when I saw that I wanted to add a function that returns true or false based on the fact if the role actually exists.
I would love to read your opinion on this pull request.
> [1.x] Added hasTeamRole check on the HasTeams trait.

- src/HasTeams.php
- src/Membership.php
- src/Team.php
If you register a **custom pivot model** for the teams-users relationship through `Jetstream::useMembershipModel()` and your model has a **custom table name** (other than the usual derived `team_user` table name), you must also override the whole membership-related relationship declarations, both `User::teams()` from [`HasTeams`](https://github.com/laravel/jetstream/blob/3ac0a23814c643b1e4de8168423e5be784081261/src/HasTeams.php#L56) and `Team::users()` from [`Team`](https://github.com/laravel/jetstream/blob/3ac0a23814c643b1e4de8168423e5be784081261/src/Team.php#L30) in your app. 
The problem is not very apparent after just customising the pivot model, as you just get an SQL error saying table `team_user` doesn't exist, thrown from the Jetstream dashboard view.
This happens because the …
> [1.x] Use explicit table names from custom pivot models

- src/Http/Livewire/LogoutOtherBrowserSessionsForm.php
Redoing [this](https://github.com/laravel/jetstream/commit/49a6815c7f0e5bb18261c7a0df86a3799328f3b3#diff-0f3801bd907dc119b7d0156b22afbc46) on the other stack.
> [1.x] Use session table from the config

- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/livewire/resources/views/navigation-dropdown.blade.php
Display user name nicer when `Features::profilePhotos()` is not enabled.
Styling matches inactive navigation items.
Upon hover or clicking, styling matches active state of other navigation items.
> [1.x] Add Submenu Style For When Profile Photos Are Unmanaged

- src/Http/Controllers/Inertia/OtherBrowserSessionsController.php
- src/Http/Controllers/Inertia/UserProfileController.php
- src/Http/Livewire/LogoutOtherBrowserSessionsForm.php
**Purpose**:
This PR provides further support for other authentication providers in Jetstream.
**Reason**:
Since the `getKey()` method is not apart of the `Authenticatable` contract, anyone attempting to use the Inertia stack in Jetstream with another authentication provider cannot do so if the authenticatable user does not implement the `getKey()` method.
**Details**:
It would be great to use the `getAuthIdentifier()` method instead of `getKey()` since the former is implemented in the Authenticatable contract when using other authentication providers in Jetstream.
**Breaking Changes**:
There are no breaking changes in this PR. The `getAuthIdentifier()` method uses the `id` database column by default on the included `App\Models\User` model. Anyone who has adjusted or modified their …
> Use getAuthIdentifier instead of getKey for compatibility with other Laravel auth providers

- stubs/resources/views/auth/forgot-password.blade.php
- stubs/resources/views/auth/login.blade.php
- stubs/resources/views/auth/register.blade.php
- stubs/resources/views/auth/reset-password.blade.php
- stubs/resources/views/auth/two-factor-challenge.blade.php
Labels will now trigger the inputs on click
> a11y(auth): associate inputs with labels

- stubs/resources/views/layouts/guest.blade.php
Ensure text remains visible during webfont load via the `display` parameter.
It is already there in the `app` layout. This PR adds the same to the `guest` layout.
> [1.x] Ensure text remains visible during webfont load

- resources/views/components/modal.blade.php
This PR adds "focus-trapping" to the modals in Jetstream.
This means that pressing "Tab" and "Shift+Tab" will only cycle through focusing elements inside the modal.
Here's a gif:
> [1.x] Add dependancy-less modal focus trapping

- stubs/app/Providers/JetstreamWithTeamsServiceProvider.php
Make JetstreamServiceProvider with teams terms translatable
> JetstreamServiceProvider - Make terms translatable

- src/HasTeams.php
- src/Http/Controllers/CurrentTeamController.php
This PR extract the logic for team switching into the `HasTeams` trait, which allows to switch the current team from code. 
__Example:__ Use the `switchTeam` method to change the current team during a test.
```php
/** @test */
public function xyz()
{
$user = User::factory()->create();
// ...
$user->switchTeam($otherTeam);
// ...
}
```
> [1.x] Extract switch team logic into HasTeams trait

- stubs/inertia/resources/js/Jetstream/ConfirmsPassword.vue
- stubs/inertia/resources/js/Layouts/AppLayout.vue
Apparently, axios requires the URL to be a string to send the CSRF header (this doesn't seem to be a problem with Inertia though). This PR fixes the issues introduced in #314.
> Fix axios routes

- stubs/livewire/resources/views/profile/show.blade.php
---
**Before**: On comment/disable updateProfileInformation as Fortify feature, it's still visible in profile and could get updated.
**After**: On comment/disable updateProfileInformation as Fortify feature, it's not anymore visible. Plus the `x-jet-section-border` I have moved inside the if statements. 
Checkout #321 
(My first PR for Laravel :blush: )
> Correct visibility of Fortify features in profile view #321

- stubs/inertia/resources/js/Pages/Profile/Show.vue
- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
The user profile is given name and email fields, but it would get the user photo url directly from the $page.
This makes it consistent to other components and much easier to add fields.
> Give user object to update profile information form

- src/HasTeams.php
- tests/TeamBehaviorTest.php
This is probably a bit minor, but I think it adds value and saves time.
When switching the current team for the user, it's not immediately ready/accessible (if I'm doing things right) when trying to access.  That is:
```php
$personalTeam = $user->personalTeam;
$user->isCurrentTeam($personalTeam); // true
$user->switchTeam($anotherTeam);
$user->isCurrentTeam($anotherTeam); // false
```
This change simply uses `setRelation()` in `switchTeam()` (h/t: @reinink) to immediately set the relation.
AFAIK, there's no downside to this.  The relation is available, so no extra effort is needed hitting the database or anything.  The upside is that there's no need for the developer to call `fresh()` or `refresh()` or whatever....nor is there any time wasted wondering why the call to `switchTeam()` …
> [1.x] Explicitly setting currentTeam relation on switchTeam to avoid refresh.

- stubs/resources/views/auth/two-factor-challenge.blade.php
Because TOTP codes are numeric I propose hinting this `inputmode` (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) to the browser. 
This make entering it easier for mobile users, as only the digitblock keyboard is shown.
> Numeric keyboard in Two Factor Challenge

- stubs/inertia/resources/js/Jetstream/Welcome.vue
- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/inertia/resources/js/Pages/API/ApiTokenManager.vue
- stubs/inertia/resources/js/Pages/API/Index.vue
- stubs/inertia/resources/js/Pages/Dashboard.vue
- stubs/inertia/resources/js/Pages/Profile/DeleteUserForm.vue
- stubs/inertia/resources/js/Pages/Profile/LogoutOtherBrowserSessionsForm.vue
- stubs/inertia/resources/js/Pages/Profile/Show.vue
- stubs/inertia/resources/js/Pages/Profile/TwoFactorAuthenticationForm.vue
- stubs/inertia/resources/js/Pages/Profile/UpdatePasswordForm.vue
- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
- stubs/inertia/resources/js/Pages/Teams/Create.vue
- stubs/inertia/resources/js/Pages/Teams/CreateTeamForm.vue
- stubs/inertia/resources/js/Pages/Teams/DeleteTeamForm.vue
- stubs/inertia/resources/js/Pages/Teams/Show.vue
- stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
- stubs/inertia/resources/js/Pages/Teams/UpdateTeamNameForm.vue
- stubs/webpack.config.js
- stubs/webpack.mix.js
With `@` alias for js folder, we can use absoulte path instead of relative.
Imports will be more clear:
```diff
-import JetLabel from './../../Jetstream/Label'
+import JetLabel from '@/Jetstream/Label'
```
Its standard practice from vue cli preset. Also, you can check out article [https://laravel-news.com/laravel-mix-alias](https://laravel-news.com/laravel-mix-alias) with example of implementation.
> [1.x] Added js directory path alias

- src/Console/InstallCommand.php
- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/inertia/resources/js/Pages/Auth/VerifyEmail.vue
- stubs/inertia/resources/js/Pages/Welcome.vue
- stubs/inertia/routes/web.php
This PR swaps out the default 'welcome' view with an Inertia one.
While it might be worth considering to keep the current scenario (as it demonstrates how a developer can easily switch between an Inertia-powered section and a Blade-powered section), this change makes the whole Inertia experience more complete and Inertia-native.
> Use Inertia-based welcome view

- src/JetstreamServiceProvider.php
This PR adds config for prefixing jetstream routes in the same pattern that is used in Laravel Fortify route binding.
This allows adding prefix like /admin to routes if the application requires changes in url structure.
> [1.x] Add Jetstream route prefix config

- composer.json
Because of changes implemented in #326, the minimum `inertiajs/inertia-laravel` version [is now `^0.3`](https://github.com/laravel/jetstream/pull/327/files#diff-5cffa5eda5bfb718c5f416e0c6e95cf6913e8a092d70581ec5f3e1dfae349941R233). 
This however isn't reflected in the `composer.json`, which might cause issues with existing installs as well as with what's displayed on packagist. Apologies for not catching this earlier!
> [2.x] Align min. inertiajs/inertia-laravel version

- src/Console/InstallCommand.php
This prevents issues with `PUT`/`POST`/`PATCH` requests due to the Middleware changes introduced in `inertiajs/inertia-laravel` `^0.3`. This is not an issue on `master`, because on that version these changes are already implemented (#327)
See https://twitter.com/don_jon243/status/1318926992645959683 for more info
> [1.x] Lock inertiajs/inertia-laravel to ^0.2.4

- src/JetstreamServiceProvider.php
- stubs/inertia/resources/js/Pages/Auth/ConfirmPassword.vue
- stubs/resources/views/auth/confirm-password.blade.php
This PR adds a stand-alone screen for password confirmation that is compatible with Laravel Fortify's support for this feature.
> Confirm Password

- src/Http/Controllers/Inertia/TeamController.php
- src/Http/Controllers/Livewire/TeamController.php
I have a need to customise whether a team should be shown. At the moment, the `TeamController` show method checks if the user `belongsToTeam` and aborts if not:
**Http\Inertia\TeamController**
**Http\LIvewire\TeamController**
```php
public function show(Request $request, $teamId)
{
$team = Jetstream::newTeamModel()->findOrFail($teamId);
if (! $request->user()->belongsToTeam($team)) {
abort(403);
}
return view('teams.show', [
'user' => $request->user(),
'team' => $team,
]);
}
```
If I want to change this, I would need to override the `TeamController` show method rather than use the original.
I inspected the code and noted that the stub and test fixture for the `TeamPolicy` already checks for `belongsToTeam`:
```php
public function view(User $user, Team $team)
{
return …
```
> [1.x] Make team show use policies

- resources/views/components/modal.blade.php
- src/Console/InstallCommand.php
- stubs/inertia/resources/js/Jetstream/Modal.vue
When using `x-jet-dialog-modal` on mobile and if the dialog has a lot of content you can't scroll to reach the content that doesn't fit in the screen.
Also the body of the document scrolls when modal is open.
This PR makes Modal scrollable when it is taller than the screen.
It is based on the #305 (it just disabled the body scrolling when modal is open) but also makes the modal itself scrollable.
It contains a hack for Firefox that can't work with `padding bottom` and `overflow: auto` as described on [SO](https://stackoverflow.com/a/38177668/3071884).
P.S. During the testing I have noticed that there's `sm:items-top` class that doesn't even exist. It should be `sm:items-start`.
Thinking about it - these classes just make the modal centered horizontally on larger screens`sm:flex …
> [1.x] Make livewire modal scrollable

- src/Http/Controllers/Inertia/TeamController.php
- src/Http/Livewire/CreateTeamForm.php
- src/Http/Livewire/DeleteTeamForm.php
- src/RedirectsActions.php
In the application I'm developing, I would like the user to be redirected to a specific page after creating or deleting a team. Currently when a new team is created or deleted, the user is redirected to path defined by the `fortify.home` configuration variable. 
In Laravel (without Jetstream) this is accomplished by implementing the `redirectTo()` method or a `$redirectTo` property on the LoginController, ResetPasswordController, etc...
My proposal is to allow customization of the redirects by allowing a `redirectTo()` method or a `$redirectTo` property on the following actions.
- CreatesTeams
- DeletesTeams
The consuming controllers would look for the existence of `redirectTo()` on the action and use it, otherwise default to `fortify.home`.
> [1.x] Adds custom redirects after creating or deleting a team

- src/Http/Livewire/DeleteTeamForm.php
Follow up to https://github.com/laravel/jetstream/pull/383
I forgot to add the trait to the DeleteTeamForm component
> [1.x] Add missing trait

- resources/views/components/banner.blade.php
- stubs/inertia/resources/js/Jetstream/Banner.vue
There is no need to wrap the message in `<span>` tag (and duplicate the content) because it's always visible, no matter of screen size.
Also, the message wasn't truncated in Firefox, and I fixed it by using `min-w-0` class on the parent element.
**Make sure to recompile the assets before testing.**
| Before 	| After 	|
|-	|-	|
| ![Zrzut ekranu 2020-10-23 o 23 24 38](https://user-images.githubusercontent.com/98191/97055638-84571580-1587-11eb-89fa-ca962f63d4cd.png) 	| ![Zrzut ekranu 2020-10-23 o 23 24 53](https://user-images.githubusercontent.com/98191/97055642-87520600-1587-11eb-877f-3dc7f92e5fab.png) 	|
> [2.x] Simplify banner component

- resources/views/components/action-message.blade.php
Component slot return always HtmlString. That's why while using <x-action-message on="saved" /> isset isn't checking & default 'saved.' text not showing. isEmpty() check could show default message.
> [1.x] Slot Empty Checking & Return Default Value

- src/Console/InstallCommand.php
Related to #392, this PR ensures that Jetstream v1 will install Ziggy `^0.9.4` (current as of today), _not_ Ziggy v1.
@mattstauffer pointed out that if a user adds Jetstream to their project now but doesn't run the `install` command for a month, they'll get Ziggy v1 which isn't compatible with Jetstream v1. Adding this version constraint will prevent that.
> [1.x] Constrain Ziggy version to ^0.9.4

- stubs/inertia/resources/js/Layouts/AppLayout.vue
This will replace the active check to use ziggy's `route().current('routename')` method.
> Use ziggy current method to check active link

- stubs/inertia/resources/js/Layouts/AppLayout.vue
The `ApplicationLogo` component is not used in the layout, so it's safe to remove the import.
> [1.x] Remove unused import

- stubs/livewire/resources/views/layouts/app.blade.php
- stubs/resources/views/layouts/guest.blade.php
Closes #384 
The issue where modals transition in, but not out when Livewire is the one to trigger the state change has been fixed in the latest versions of Livewire and Alpine:
Livewire: v2.3.1
Alpine: v2.7.3
The original issue should be partially fixed in older versions of Alpine (for existing installs), but a few more edge cases have been addressed that will only be fixed for people running Alpine 2.7.3 and above.
Namely, without 2.7.3 there are few transition interruption edge cases.
For example: if a user closes a modal in Jetstream, and while it's transitioning out, they somehow re-open it, it will disappear.
I'm not even sure if this case is possible to re-create in Jetstream, but just noting it here.
> [1.x] Fix Livewire Modal Closing Issue By Bumping Alpine To 2.7.3

- src/HasProfilePhoto.php
- stubs/app/Actions/Jetstream/DeleteUser.php
- stubs/app/Actions/Jetstream/DeleteUserWithTeams.php
- tests/Fixtures/User.php
When a user deletes an account, the image will now be deleted as well. fixes #396
> [1.x] Delete the users profile picture

- stubs/app/Actions/Jetstream/DeleteUser.php
- stubs/app/Actions/Jetstream/DeleteUserWithTeams.php
Currently if a user is deleted, their api tokens will remain inside the database. The api tokens are now deleted at the same time the user will be deleted.
> Delete user tokens when user is deleted

- src/Console/InstallCommand.php
This PR fixes an issue where Composer (1.x?) runs out of memory while Jetstream installs stack-dependent packages.
I personally ran into this issue a few weeks ago, but after seeing others on the Inertia.js discord run into it today, I decided to PR it.
Basically, what they'll see is the following:
```
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/Cellar/composer/1.10.8/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/Cellar/composer/1.10.8/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52
```
By setting the …
> [1.x] Fix composer memory limit crashes

- .github/workflows/tests.yml
- composer.json
Dependencies updated to support PHP8:
Dependencies missing:
> PHP8 Support

- stubs/livewire/resources/views/profile/two-factor-authentication-form.blade.php
I had an issue where I couldn't scan the barcode when setting up 2FA. Determined the issue was using darkmode tailwind css styling. The Google authenticator app and VIP Access Authenticator don't pick up the barcode if it has a dark background right up against it. Add a p-4 white background resolved the issue on both apps. Propose adding this white border out of the box to prevent this issue if the user chooses a dark color adjacent to the barcode.
> [1.x] Update two-factor-authentication-form.blade.php

- stubs/inertia/resources/js/Pages/Profile/TwoFactorAuthenticationForm.vue
Adding matching styles for fix applied to Livewire to resolve issue with QR code not being read by authenticator if back ground is dark and right up against QR Code image.
> [1.x] Update TwoFactorAuthenticationForm.vue

- stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
- stubs/livewire/resources/views/teams/team-member-manager.blade.php
This pull request proposes that the **Add Team Member** section **Role** options are changed to Buttons instead of Div's. Making this change will increase Accessibility and will allow the end-users to select a Role using the keyboard and not just the mouse.
Tailwind focus border styles have been applied to improve accessibility and the loop has been modified to allow for rounded corners as appropriate in the button grouping.
I've made changes to both the Livewire and Inertia stubs.
> [2.x] Accessibility Keyboard Navigation Improvements for Add Team Member Role Options

- stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
- stubs/livewire/resources/views/teams/team-member-manager.blade.php
Accessibility fix. PR changes the ID of the Input to match the Email Label. Issue only applies to Livewire stubs, the Inertia stub looks fine.
Accessibility update, Added Keyboard Navigation to Team Role Management Modals by converting Div to Button and applied Tailwind focus styles. Same as the previous PR that was already merged yesterday but this time for the Modals. This update includes Inertia and Livewire stubs.
> [2.x] Accessibility Update, Keyboard Nav for Team Role Modals and Fix ID for Email Input

- stubs/inertia/resources/js/Pages/API/ApiTokenManager.vue
- stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
- stubs/livewire/resources/views/api/api-token-manager.blade.php
- stubs/livewire/resources/views/teams/team-member-manager.blade.php
This PR removes the **outline-none** style from the Remove and Leave buttons on the Team Member Manager pages. The role button currently has the button outline but the remove/leave button does not. Currently when you tab from the Role button you cannot see that the Remove button has been selected. Removing outline-none will be more consistent and be more accessible.
This PR also removes outline-none style from the API token Permissions and Delete buttons for the same reasons.
> [2.x] Accessibility improvement. Remove outline-none style from Remove and Leave Buttons 

- stubs/inertia/resources/js/Pages/Profile/Show.vue
Profile page isn't accessible because of invalid key name:
> [Vue warn]: Error in render: "TypeError: Cannot read property 'hasAccountDeletionFeatures' of undefined"
> [2.x] Fix invalid key name

- src/Console/InstallCommand.php
- stubs/inertia/resources/js/Jetstream/ConfirmsPassword.vue
This PR makes Jetstream's Inertia preset compatible with Ziggy v1, which will be released shortly.
I _think_ this has to target Jetstream v2, because for anyone who has already installed Jetstream (and therefore Ziggy v0.9.4), this would be a breaking change that would require them to manually upgrade their whole app to Ziggy v1. If Jetstream users publish all these components immediately, and changing them here would not update them for existing installs, then I guess technically it isn't a breaking change, but I think it could still be confusing.
Since the Inertia preset installs `tightenco/ziggy` with no version constraint, it will start installing Ziggy v1 as soon as it's tagged, so ideally this change would be merged right after we tag it. I'm opening a PR now so that it's on your …
> [2.x] Update for Ziggy v1

- src/Console/InstallCommand.php
- stubs/inertia/resources/js/app.js
- stubs/inertia/resources/views/app.blade.php
- stubs/livewire/resources/views/layouts/app.blade.php
- stubs/resources/js/app.js
- stubs/resources/views/layouts/guest.blade.php
Two things in this PR:
- Use the `mix` helper wherever possible to support hot reloading (see https://github.com/laravel/jetstream/pull/217)
- This removes the CDNs in favor of a dedicated installed NPM library. See the reasoning below.
As for the alpine.js import it's the same reasoning as here: https://github.com/laravel/breeze/pull/10. I realize the Livewire stack technically doesn't needs JS except for Alpine but this way all libraries are imported the same locally and Alpine's version number can be managed in one place instead of multiple. Another reasoning is that if developers *do* want to make use of JavaScript in their Livewire app, this setup makes that just a bit more easier for them to do so. I've left the import of the `bootstrap.js` file out for the Livewire stack.
I've …
> [1.x] Use mix helper and remove CDNs

- stubs/inertia/resources/js/Pages/Auth/VerifyEmail.vue
Remove unused form params in VerifyEmail.vue (looks like it was copy/pasted from Login.vue)
> Remove unused form params

- src/Http/Middleware/ShareInertiaData.php
This *breaking change* pull request removes the `currentRouteName` shared inertia data since the active route check was replaced with ziggy's `current()` method here https://github.com/laravel/jetstream/pull/402.
> [2.x] Remove unused shared inertia data

- stubs/resources/views/auth/register.blade.php
Placeholders should not be used as a replacement for HTML tags.
Instead, I propose to use two placeholders - `terms_of_service` and `privacy_policy` - which can be replaced with either a link, or a text. Thanks to this, we can also reuse existing translations for `Terms of Service` and `Privacy Policy` if they were previously defined in our app.
> [2.x] Improve translation string

- src/Http/Controllers/Inertia/ApiTokenController.php
Return back with 303 when requesting with DELETE  and PUT to prevent 405 on the subsequent request.
`back()` returns 302 by default.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303
https://inertiajs.com/redirects
> [1.x] Updating response status code to prevent method not allowed

- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/livewire/resources/views/navigation-dropdown.blade.php
This pull request adds verification that Jetstream's `profilePhotos` feature is enabled in order to display the photo in mobile navigation; today, this check exists only for desktop navigation, trying to show the profile picture on the responsive navigation even if the feature is disabled.
Screenshots 📸 
> Tests performed with the `profilePhotos` feature **disabled**.
Without the verification             |  With the verification
:-------------------------:|:-------------------------:
> [2.x] Checking for photos feature in mobile navigation

- stubs/resources/views/layouts/guest.blade.php
This reverts a small part of https://github.com/laravel/jetstream/pull/450. What happened was that because the guest layout isn't an SPA in Inertia the console starts to throw errors because it cannot resolve routes. This is technically solved in Jetstream v2 where the guest layout isn't copied anymore and all views are Inertia scripts. But for Jetstream 1.x we'll need to reference Alpine directly instead of loading in the entire `app.js` on the guest layout.
I have to note that nothing was actually broken, just the console which was showing the errors from the screenshots in the issue below.
Fixes https://github.com/laravel/jetstream/issues/482
> [1.x] Use Alpine directly for guest layout

- src/Http/Livewire/DeleteUserForm.php
It's a small change, but it should be OK.  🤓 
Previously, there was a **very minor** issue if the following steps were followed:
- log in
- navigate to profile
- delete account
- enter incorrect password
- note the validation error message
- close confirmation window via ESC or Nevermind
- delete account...again
The issue: the validation error message is still displayed.
I've simply added `$this->resetErrorBag();` to make sure that validation errors are cleared each time the user attempts to delete their account.
Please let me know if there are any problems/questions.  Thx...!  🤓
> Clears any validation error message before re-displaying confirmation

- resources/views/components/checkbox.blade.php
- resources/views/components/dropdown.blade.php
- resources/views/components/input.blade.php
- src/Console/InstallCommand.php
- src/JetstreamServiceProvider.php
- stubs/inertia/resources/js/Jetstream/Checkbox.vue
- stubs/inertia/resources/js/Jetstream/Dropdown.vue
- stubs/inertia/resources/js/Jetstream/Input.vue
- stubs/inertia/resources/js/Pages/API/ApiTokenManager.vue
- stubs/inertia/resources/js/Pages/Auth/Login.vue
- stubs/inertia/resources/js/Pages/Auth/Register.vue
- stubs/inertia/resources/js/Pages/Welcome.vue
- stubs/inertia/tailwind.config.js
- stubs/inertia/webpack.mix.js
- stubs/livewire/resources/views/api/api-token-manager.blade.php
- stubs/livewire/tailwind.config.js
- stubs/livewire/webpack.mix.js
- stubs/resources/views/auth/login.blade.php
- stubs/resources/views/auth/register.blade.php
This PR upgrades Jetstream stacks to use Tailwindcss v2
> [2.x] Tailwind 2

- src/Console/InstallCommand.php
- src/Contracts/RemovesTeamMembers.php
- src/Http/Controllers/Inertia/TeamMemberController.php
- src/Http/Livewire/TeamMemberManager.php
- src/Jetstream.php
- stubs/app/Actions/Jetstream/RemoveTeamMember.php
- stubs/app/Providers/JetstreamWithTeamsServiceProvider.php
- tests/RemoveTeamMemberTest.php
This PR publishes the `RemoveTeamMember` action, allowing develops to tap into the functionality of what happens when you remove a team member.
_For the purposes of this PR, we consider an application where users can create either personal or team "reports". When a user creates a team report, they also own that report, only they can remove it_
1. User 1 (admin) invites User 2 (editor) to a team.
2. User 2 creates a team report.
3. User 1 removes user 2 from the team, but the report remains part of the team and owned by the user 2.
In this scenario, the remove team member functionality should allow developers to determine what happens to the report that user 2 is the owner of. (For example, programmatically make user 1 (the admin, and remover of user 2) the new owner of that report. …
> [2.x] Publish "RemoveTeamMember" to allow it to be modified

- src/Http/Livewire/TeamMemberManager.php
The latest PR merged included the RemovesTeamMembers contract.
In the removeTeamMember method, a typos was introduced.
Thanks to @joelbutcher btw, it was the missing feature for me :]
> [2.x] Fix RemovesTeamMembers typos

- database/migrations/2020_05_21_300000_create_team_invitations_table.php
Because it should be:
- https://github.com/laravel/jetstream/blob/master/database/migrations/2020_05_21_200000_create_team_user_table.php#L20
- https://github.com/laravel/jetstream/blob/master/stubs/app/Actions/Jetstream/InviteTeamMember.php#L72
> [2.x] Set role nullable on team invitations table

- src/JetstreamServiceProvider.php
This changes the config key used to determine the prefix for Jetstream routes from `path` to `prefix`. This keeps it consistent with the same config key used in Fortify (see https://github.com/laravel/fortify/blob/1.x/src/FortifyServiceProvider.php#L128).
> [1.x] Rename path to prefix for route config

- stubs/inertia/webpack.mix.js
- stubs/livewire/webpack.mix.js
Quote from Laravel Docs, which is true:
> Because versioned files are usually unnecessary in development, you may instruct the versioning process to only run during npm run production
Link - https://laravel.com/docs/8.x/mix#versioning-and-cache-busting
The same in laravel-mix docs - https://laravel-mix.com/docs/5.0/versioning#optionally-versioning-files
Related to - https://github.com/laravel/jetstream/pull/502
> [2.x] Enable assets versioning only in production

- src/Console/InstallCommand.php
- src/Jetstream.php
- src/Team.php
- stubs/app/Models/TeamInvitation.php
Like all other models in Jetstream, TeamInvitation should be easily overridable.
A basic use case occurs when we don't want to send an email invitation but notify the user with another method (in-app notification for example).
In that case, we should be able to remove the email field and add another field to identify the user and send him the invitation the way we want using the already overridable `InvitesTeamMembers` contract.
*In the same time I fixed a (not-mine) typo in -probably- copy/pasted comment*
> [2.x] Allows to use a custom TeamInvitation Model

- stubs/inertia/resources/js/app.js
When the user changes language, it's correctly reflected in the `vue-i18n` plugin (using the `success` event), but the `lang` attribute in the `<html>` tag remains unchanged until the page is fully refreshed.
> [2.x] Update lang attribute

- stubs/app/Models/UserWithTeams.php
This is similar to #182 but for when `--teams` is enabled.
> [1.x] add missing import must verify email interface

- stubs/inertia/resources/js/Pages/Teams/Create.vue
This PR removes unused `JetSectionBorder` component and the `team` prop:
https://github.com/laravel/jetstream/blob/master/src/Http/Controllers/Inertia/TeamController.php#L57
> [2.x] Cleanup team creation page

- src/Actions/ValidateTeamDeletion.php
Inertia uses the `deleteTeam` bag when making the request, but the name is missing in the `ValidateTeamDeletion` action.
https://github.com/laravel/jetstream/blob/master/stubs/inertia/resources/js/Pages/Teams/DeleteTeamForm.vue#L72
It can be useful for showing the error in the modal window.
> [2.x] Set the error bag name

- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
Livewire version uses the user's name in the `alt` attribute:
https://github.com/laravel/jetstream/blob/master/stubs/livewire/resources/views/profile/update-profile-information-form.blade.php#L31
> [2.x] Use name in the alt attribute

- src/Actions/UpdateTeamMemberRole.php
- src/Events/TeamMemberUpdated.php
This PR adds a new `TeamMemberUpdated` event. The event get's dispatched at the end of the `UpdateTeamMemberRole` action.
As an example, developers might want to notify a user that their privileges have changed. Now that can do this more easily by reacting to this event.
> [2.x] Team member updated event

- src/Console/InstallCommand.php
- src/Http/Middleware/ShareInertiaData.php
- stubs/inertia/resources/js/Jetstream/Banner.vue
- stubs/inertia/resources/js/Jetstream/ConfirmsPassword.vue
- stubs/inertia/resources/js/Jetstream/ValidationErrors.vue
- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/inertia/resources/js/Pages/API/ApiTokenManager.vue
- stubs/inertia/resources/js/Pages/API/Index.vue
- stubs/inertia/resources/js/Pages/Auth/ConfirmPassword.vue
- stubs/inertia/resources/js/Pages/Auth/ForgotPassword.vue
- stubs/inertia/resources/js/Pages/Auth/Login.vue
- stubs/inertia/resources/js/Pages/Auth/Register.vue
- stubs/inertia/resources/js/Pages/Auth/ResetPassword.vue
- stubs/inertia/resources/js/Pages/Auth/TwoFactorChallenge.vue
- stubs/inertia/resources/js/Pages/Auth/VerifyEmail.vue
- stubs/inertia/resources/js/Pages/Dashboard.vue
- stubs/inertia/resources/js/Pages/Profile/DeleteUserForm.vue
- stubs/inertia/resources/js/Pages/Profile/LogoutOtherBrowserSessionsForm.vue
- stubs/inertia/resources/js/Pages/Profile/Show.vue
- stubs/inertia/resources/js/Pages/Profile/TwoFactorAuthenticationForm.vue
- stubs/inertia/resources/js/Pages/Profile/UpdatePasswordForm.vue
- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
- stubs/inertia/resources/js/Pages/Teams/Create.vue
- stubs/inertia/resources/js/Pages/Teams/CreateTeamForm.vue
- stubs/inertia/resources/js/Pages/Teams/DeleteTeamForm.vue
- stubs/inertia/resources/js/Pages/Teams/Show.vue
- stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
- stubs/inertia/resources/js/Pages/Teams/UpdateTeamNameForm.vue
- stubs/inertia/resources/js/app.js
- stubs/inertia/webpack.config.js
This PR reverts the internationalization changes that were introduced to `2.x` earlier this year, for multiple reasons:
- Lots of people don't use translations in their apps at all, as they are not targeting an international audience.
- The implementation has a lot of surface area, and it's configuration makes a 'clean install' look overly complex.
- Third-party translation services might not support/use vue i18n, forcing you to re-do the integration anyway.
- Implementing Vue i18n yourself does not take too much time.
> [2.x] Inertia: Revert default Vue i18n implementation

- src/Console/InstallCommand.php
- src/Http/Controllers/Inertia/ApiTokenController.php
- stubs/inertia/resources/js/Pages/API/ApiTokenManager.vue
- stubs/inertia/resources/js/app.js
While cleaning up the `app.js`, I noticed that the `moment` library was included, but was only being used once.
Because Inertia gets it's state from the back-end, we can instead let Carbon do this conversion for us and pass it through to the front-end and remove the (fairly large) `moment` dependency entirely.
> [2.x] Inertia: Remove moment.js dependency

- src/Console/InstallCommand.php
- src/Http/Controllers/Inertia/ApiTokenController.php
- src/Http/Controllers/Inertia/CurrentUserController.php
- src/Http/Controllers/Inertia/OtherBrowserSessionsController.php
- src/Http/Middleware/ShareInertiaData.php
- stubs/inertia/resources/js/Jetstream/ConfirmsPassword.vue
- stubs/inertia/resources/js/Jetstream/ValidationErrors.vue
- stubs/inertia/resources/js/Pages/API/ApiTokenManager.vue
- stubs/inertia/resources/js/Pages/Auth/ConfirmPassword.vue
- stubs/inertia/resources/js/Pages/Auth/Login.vue
- stubs/inertia/resources/js/Pages/Auth/Register.vue
- stubs/inertia/resources/js/Pages/Auth/ResetPassword.vue
- stubs/inertia/resources/js/Pages/Auth/VerifyEmail.vue
- stubs/inertia/resources/js/Pages/Profile/DeleteUserForm.vue
- stubs/inertia/resources/js/Pages/Profile/LogoutOtherBrowserSessionsForm.vue
- stubs/inertia/resources/js/Pages/Profile/TwoFactorAuthenticationForm.vue
- stubs/inertia/resources/js/Pages/Profile/UpdatePasswordForm.vue
- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
- stubs/inertia/resources/js/Pages/Teams/CreateTeamForm.vue
- stubs/inertia/resources/js/Pages/Teams/DeleteTeamForm.vue
- stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
- stubs/inertia/resources/js/Pages/Teams/UpdateTeamNameForm.vue
- stubs/inertia/resources/js/app.js
This PR upgrades Jetstream to support and make use of the features shipped with `@inertiajs/inertia-vue` version `0.5.0`.
Specifically, it migrates away from [`jetstream-js`](https://github.com/laravel/jetstream-js) in favor of Inertia's own form helper, removes explicit 'error bag' definitions where possible, and also fixes a couple other minor issues found during this migration.
> [2.x] Upgrade Inertia

- stubs/inertia/resources/js/Jetstream/Dropdown.vue
Avoid using '==' when possible and when compared to user input.
This fixes 'eqeqeq' error in eslint : https://eslint.org/docs/rules/eqeqeq
This fix is harmless and can be applied to 2.x
> [1.x] Avoids eqeqeq errors in eslint

- UPGRADE.md
Some minor updates to the guide:
- Anchors aren't needed as these are generated by GitHub itself
- Version in composer needs to be without the last `.0` to allow upgrades for minor versions
- Anchors to stubs need to have `2.x` in their link instead of master when we branch of the new 2.x release
- Fixed an incorrect reference to the `TeamInvitation` model stub
- I remove the "Upgrade Guide" part from the stack titles as I felt this was more of a given and not necessary to have in these titles. Bit cleaner.
> [2.x] Update UPGRADE.md

- resources/views/mail/team-invitation.blade.php
Made the text on the buttons in the team invitation email translatable.
> [2.x] Make button text in team invitation email translatable

- UPGRADE.md
- src/JetstreamServiceProvider.php
This PR adds a new `jetstream-v2-inertia-files` tag to the service provider, allowing developers using the Inertia stack, looking to upgrade from 1.x to 2.x, to migrate their authentication views over to Vue.
```sh
php artisan vendor:publish --tag=jetstream-v2-inertia-files
```
> [2.x] Allow publishing of missing Inertia files

- .github/ISSUE_TEMPLATE/1_Bug_report.md
Just so we can scaffold the right app when reproducing bugs.
> [2.x] Ask if app uses teams in bug report

- src/Console/InstallCommand.php
Adds the optional `--composer` option to the install command. This option may receive a path pointing to a specific composer binary. As proposed in PR #588.
```
php artisan jetstream:install livewire --composer=composer.phar
php artisan jetstream:install livewire --teams --composer=composer.phar
```
This is useful for systems where no global composer binary is installed.
> [2.x] Add --composer option to the install command

- stubs/app/Actions/Jetstream/CreateTeam.php
- tests/TeamBehaviorTest.php
Current behaviour is when a new team is created you are redirected back to the dashboard of the team that you were in before creating the new. In almost all cases a users next action would be directed against the new team.
This PR solves that problem by modifying the CreateTeam class and updating the current_team_id param on the user model of the user creating the team. This way when the user is redirected back they are acting in the context of the newly created team.
> [2.x] Change current team of user when creating a new additional team

- src/Http/Controllers/Inertia/OtherBrowserSessionsController.php
- src/Http/Controllers/Inertia/UserProfileController.php
- src/Http/Livewire/LogoutOtherBrowserSessionsForm.php
When using sessions in a separate database connection, the sessions table is not found when querying or deleting sessions. This pull request takes the session.connection supplied in the config, so the session management for Jetstream can follow the users configs and/or .env values for session connection.
The changes has been made both for Inertia and Livewire stack. 
Should be no breaking changes as it uses the same way Laravel/framework gets the session connection in the session manager: https://github.com/laravel/framework/blob/28e0f61bba1cbc727383d183b7116eb723de7660/src/Illuminate/Session/SessionManager.php
line: 99
> [2.x] Jetstream ignoring sessions from session connection in config

- stubs/tests/RegistrationTest.php
This PR fixes Registration Test when Terms of Services feature is enabled.
Previously when running the Registration Test with Terms of Services feature enabled it was failing because the `terms` attribute it wasn't presented.
> [Fix] RegistrationTest for Terms of Services

- stubs/inertia/resources/js/Jetstream/Modal.vue
Add z-index to the modal so it doesn't overlap with other elements.
> Add z-index to the modal

- stubs/tests/inertia/DeleteAccountTest.php
- stubs/tests/livewire/DeleteAccountTest.php
The tests for `DeleteAccountTest` are always executed. Therefore tests fail when Account Deletion Features are disabled.
With this PR DeleteAccountTests are skipped when the feature is deactivated.
> Skip DeleteAccountTest if feature is not enabled

- src/Http/Controllers/Inertia/PrivacyPolicyController.php
- src/Http/Controllers/Inertia/TermsOfServiceController.php
- src/Http/Controllers/Livewire/PrivacyPolicyController.php
- src/Http/Controllers/Livewire/TermsOfServiceController.php
This enables the GithubFlavoredMarkdownExtention for CommonMark. GFM is included in CommonMark and only has to be enabled to allow a list of markdown features:
- Autolinks
- Disallowed Raw HTML
- Strikethrough
- Tables
- Task Lists
**Reasoning for enabling this by default**
I feel like especially the Tables functionality is something that can benefit many users attempting to set up terms through Jetstream. These documents often include tables, and enabling this extension allows for printing them on the terms pages.
> Enabling Github Flavored Markdown for Terms and Privacy Policy

- stubs/inertia/resources/js/Layouts/AppLayout.vue
On Jetstream Inertia when creating a Page component with no #header slot, the AppLayout display an empty unnecessary header instead of no header.
Before:
After:
> [2.x] Hide AppLayout header if no slot defined in Page component

- stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
- stubs/livewire/resources/views/teams/team-member-manager.blade.php
I believe that replacing the Name with Email for the form Add Team Member would be appropriate in this case.
> [2.x] Replacing the Name type with the Email type for Member Email input to Add Team Member form

- UPGRADE.md
When the package is left installed, it causes the following error to be thrown:
```
Uncaught (in promise) TypeError: this.inertiaPage().errorBags is undefined
```
> Remove laravel-jestream package when upgrading

- config/jetstream.php
- src/HasProfilePhoto.php
Jetstream always uses `public` filesystem to store the profile photos if it's not running within Laravel Vapor.
In my case, I use Google Cloud Storage, so there is no way to tell Jetstream about that.
I know that I can modify the `filesystems.disks.public.driver` to point to GCS, but it'll break the dev. environment.
Therefore we should have the profile disk as a config, so we can change it to the appropriate value.
> [2.x] Add profile_photo_disk config option

- resources/views/components/dropdown.blade.php
To keep code duplication to a minimum, people re-use components from jet stream, for example the dropdown, currently the dropdown only has a pre-set alignment, a person may want to show the dropdown on the left-side on mobile phones, but to the right on a web browser. Currently they don't have an option for that. So; with this PR they could do the following:
```
<x-jet-dropdown align="other" width="60" dropdownClasses="left-0 md:right-0">
// ....
</x-jet-dropdown>
```
> [2.x] Allow custom classes on the dropdown class

- src/Http/Controllers/Inertia/TeamController.php
- src/Http/Controllers/Livewire/TeamController.php
These routes are still accessible atm even if their policy returns false.
Fixes https://github.com/laravel/jetstream/issues/665
> [2.x] Fix permissions for team create routes

- resources/views/components/form-section.blade.php
- stubs/inertia/resources/js/Jetstream/FormSection.vue
Hi,
I found issue with form section when it has small height and we have bigger elements inside it that overextends
the height of the form section. For example datapicker, dropdown etc. I attached screen below to show the issue.
My pull request fix that issue by slightly change the classes in form section components.
I have modified inertia and livewire component.
> [2.x] Fix overflow hidden issue with overlaping elements inside form section

- src/HasTeams.php
Hi,
due to the fact that Jetstream allows to bind this trait to any models (not only User), the foreign key shouldn't be hardcoded.
My use-case:
I'm building a game where an User can have many Character. Character belongs to Team, so my foreign key is `character_id`
> [2.x] Fix ownsTeam when applied to non-User model

- src/Http/Livewire/UpdateTeamNameForm.php
Hydrate UpdateTeamNameForm Livewire Component's state with complete team attributes instead of just name. Inertia already shares all team attributes.
This change will help the developer to 'show' attributes other than just name in Team Update Form in Livewire. Currently, the developer could update the team attribute to the database without this change. This change is so developers won't have to resort to registering custom Livewire components.
> [2.x] Allow UpdateTeamNameForm in Livewire to hydrate all Team attributes

- src/Console/InstallCommand.php
- stubs/inertia/resources/js/Jetstream/ActionMessage.vue
- stubs/inertia/resources/js/Jetstream/Checkbox.vue
- stubs/inertia/resources/js/Jetstream/ConfirmationModal.vue
- stubs/inertia/resources/js/Jetstream/ConfirmsPassword.vue
- stubs/inertia/resources/js/Jetstream/DialogModal.vue
- stubs/inertia/resources/js/Jetstream/Dropdown.vue
- stubs/inertia/resources/js/Jetstream/FormSection.vue
- stubs/inertia/resources/js/Jetstream/Input.vue
- stubs/inertia/resources/js/Jetstream/Modal.vue
- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/inertia/resources/js/Pages/API/ApiTokenManager.vue
- stubs/inertia/resources/js/Pages/Auth/Login.vue
- stubs/inertia/resources/js/Pages/Auth/Register.vue
- stubs/inertia/resources/js/app.js
- stubs/inertia/resources/views/app.blade.php
Upgrade Inertia stack from VueJS v2 to VueJS v3
> [3.x] Upgrade VueJS to version 3

- database/factories/UserFactory.php
Just noticed that the ```jetstream:install``` artisan command overrides the default UserFactory from the standard Laravel installation. So, this PR brings over the unverified state that I contributed in laravel/laravel#5533 to Jetstream's UserFactory.
> [2.x] Add unverified state to UserFactory

- resources/views/components/confirms-password.blade.php
- stubs/inertia/resources/js/Jetstream/ConfirmsPassword.vue
- stubs/inertia/resources/js/Pages/API/ApiTokenManager.vue
- stubs/inertia/resources/js/Pages/Profile/DeleteUserForm.vue
- stubs/inertia/resources/js/Pages/Profile/LogoutOtherBrowserSessionsForm.vue
- stubs/inertia/resources/js/Pages/Teams/DeleteTeamForm.vue
- stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
- stubs/livewire/resources/views/api/api-token-manager.blade.php
- stubs/livewire/resources/views/profile/delete-user-form.blade.php
- stubs/livewire/resources/views/profile/logout-other-browser-sessions-form.blade.php
- stubs/livewire/resources/views/teams/delete-team-form.blade.php
- stubs/livewire/resources/views/teams/team-member-manager.blade.php
"Nevermind" isn't really a word, but at a minimum, it's not a verb; the usage in a button should be "Never Mind". This PR replaces all uses of the former with the latter.
Apologies if this was meant to be an homage to Kurt Cobain and I'm ruining it 😉.
> Replace Nevermind with Never Mind

- src/HasTeams.php
I'm guessing there's a higher chance of people having installed the illuminate/support than illuminate/collections
Fixing this docblock will help IDEs like PhpStorm using autocompletion.
> Fix typehint

- stubs/inertia/resources/js/Jetstream/ConfirmsPassword.vue
- stubs/inertia/resources/js/Pages/API/ApiTokenManager.vue
- stubs/inertia/resources/js/Pages/Profile/DeleteUserForm.vue
- stubs/inertia/resources/js/Pages/Profile/LogoutOtherBrowserSessionsForm.vue
- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
- stubs/inertia/resources/js/Pages/Teams/DeleteTeamForm.vue
- stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
This PR contains changes for Inertia vue stubs.
Based on vue3 recommended rules, the `.native` modifier on `v-on` directive is deprecated, according to the vue eslint rulesets https://eslint.vuejs.org/rules/no-deprecated-v-on-native-modifier.html it seems that in vue3 we can use the `v-on` directive on custom components as well.
> [2.x] - Remove '.native' deprecated modifier in vue3

- resources/views/components/modal.blade.php
This PR contains a micro-optimisation, but a nice one.
Right now, if you close the modal with `esc` a network request is being made. 
By using `defer`, no network request will be made when hitting escape. I've confirmed this improved behaviour in one of my projects.
Livewire docs on `defer` are here: https://laravel-livewire.com/docs/2.x/alpine-js#extracting-blade-components
> Prevent network request when pressing escape to close modal

- stubs/tests/inertia/ApiTokenPermissionsTest.php
- stubs/tests/inertia/CreateApiTokenTest.php
- stubs/tests/inertia/DeleteApiTokenTest.php
- stubs/tests/livewire/ApiTokenPermissionsTest.php
- stubs/tests/livewire/CreateApiTokenTest.php
- stubs/tests/livewire/DeleteApiTokenTest.php
Add a condition in the Inertia and Livewire tests to only test team features if Teams have been enabled. At present, some tests are failing because they expect teams to always be enabled.
This is my first, proper, PR for Laravel, so, if there is a better way to address this issue (like making `withPersonalTeam()` return null if the teams feature isn't enabled), I'm more than happy to head down that path, just point me in that direction!
> Test team features only when active

- src/Http/Middleware/ShareInertiaData.php
The inertia middleware which is used to share data to the frontend currently runs 3 queries to load all teams and the current team. 
1. Load all owned teams
2. Merge all other teams 
3. Load the currentTeam
However, this PR removes the last query since the currentTeam is one of the teams that's loaded in allTeams. This might just be a slight performance improvement! I hope it's worth merging into Jetstream.
> Reduce amount of queries for Teams feature

- stubs/inertia/resources/js/Jetstream/DropdownLink.vue
PR adds `<a>` tag to the `<jet-dropdown-link>` component.
When adding spark billing, it would be cleaner to:
```html
<jet-dropdown-link as="a" :href="route('spark.portal')">
Billing
</jet-dropdown-link>
```
compared to manually adding the tailwind classes to `<a>` to avoid inertia navigation.
```html
<a :href="route('spark.portal')" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out">
Billing
</a>
```
Used `as="a"` to stay in line with `as="button"`
> [2.x] Add a tag dropdown link

- src/Console/InstallCommand.php
- stubs/inertia/webpack.mix.js
- stubs/livewire/webpack.mix.js
Installing Jetstream requires `autoprefixer` in the `package.json` file, as well as requires it explicity in the `webpack.mix.js` file. 
However, I don't believe this is required.
[Laravel Mix will run CSS through Autoprefixer by default](https://laravel-mix.com/docs/6.0/autoprefixer), and as such it's not explicitly required in [Tailwind's Laravel installation page either](https://tailwindcss.com/docs/guides/laravel).
Removing this shouldn't affect the end build at all, just means we're not installing unnecessary boilerplate.
> [2.x] Don't require autoprefixer

- stubs/inertia/resources/js/Jetstream/Modal.vue
Modals with inertia forms that `preserveScroll: false` won't scroll top on error without `scroll-region`
Docs: https://inertiajs.com/scroll-management#scroll-regions
> [2.x] Add scroll-region to modal

- stubs/inertia/resources/js/Jetstream/Modal.vue
**Problem:**
Components within modals render when `<jet-modal :show="false">` currently.
**Effects:** 
- modals with components that request data on mount.. fires on page load
- modals with forms partially completed, closed, reopened.. not fresh form
**Solution:**
Adding `v-if` to the `<slot>` insures the the `v-show` still transitions but slot contents render each `open`
> [2.x] Load modal slot on show

- UPGRADE.md
Just noticed a missing namespace on the upgrade guide
> Request namespace may also need to be imported

- resources/views/components/section-title.blade.php
- stubs/inertia/resources/js/Jetstream/SectionTitle.vue
PR allows content in the top right of the `jet-section-title` component
Got inspiration from [Laravel Vapor's UI](https://vapor.laravel.com/#:~:text=Multiple%20Environments) & found it very useful as a default
I referred to it as `aside` incase anyone moves the slot to the left for RTL
---
Works nicely with / without, mobile, `jet-button`, `jet-dropdown` & `form-select`
---
Vue
```html
<jet-section-title class="mb-5">
<template #title>Posts</template>
<template #description>Here are the posts</template>
<template #aside>
<jet-secondary-button @click="$inertia.visit(route('posts.create'))">
New Post
</jet-secondary-button>
</template>
</jet-section-title>
```
Livewire
```html
<x-jet-section-title>
<x-slot name="title">Posts</x-slot>
<x-slot name="description">Here are the posts</x-slot> …
```
> [2.x] Add section title aside slot 

- resources/views/components/banner.blade.php
- resources/views/components/button.blade.php
- resources/views/components/danger-button.blade.php
- resources/views/components/dropdown-link.blade.php
- resources/views/components/nav-link.blade.php
- resources/views/components/responsive-nav-link.blade.php
- resources/views/components/secondary-button.blade.php
- stubs/inertia/resources/js/Jetstream/Banner.vue
- stubs/inertia/resources/js/Jetstream/Button.vue
- stubs/inertia/resources/js/Jetstream/DangerButton.vue
- stubs/inertia/resources/js/Jetstream/DropdownLink.vue
- stubs/inertia/resources/js/Jetstream/NavLink.vue
- stubs/inertia/resources/js/Jetstream/ResponsiveNavLink.vue
- stubs/inertia/resources/js/Jetstream/SecondaryButton.vue
- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/livewire/resources/views/navigation-menu.blade.php
`transition` utility-class has `duration-150` and `ease-in-out` properties by default. Therefore single `transition` utility-class produce the same thing as before unless different duration and easing being used.
> [2.x] - Remove unnecessary classes

- src/RedirectsActions.php
This PR allows users to use `Inertia::location` in redirect actions. Since that response is not directly a `RedirectResponse` (see https://inertiajs.com/redirects#external-redirects) it could not be used so far. Sometimes this kind of response is necessary to force a complete reload.
> [2.x] Accept any type of response in RedirectsActions trait

- resources/views/mail/team-invitation.blade.php
> [2.x] Fixes an error when sending email invitations when Fortify's registration feature is turned off

- src/Http/Livewire/DeleteUserForm.php
This is my first PR to a Laravel repo so please let me know if I'm doing anything incorrectly here.
All this pull request is doing is ensuring there is a session (with a single `if` statement) before attempting to destroy it in `src/Http/Livewire/DeleteUserForm.php`. 
```php
if ($request->hasSession()) {
$request->session()->invalidate();
$request->session()->regenerateToken();
}
```
Previously either of these two lines would break the TestableLivewire in [stubs/test/livewire/DeleteAccountTest.php:24](https://github.com/laravel/jetstream/blob/39d50ec0dda28ae2077baf9df307509a09307d75/stubs/tests/livewire/DeleteAccountTest.php#L24)
```php
$request->session()->invalidate();
$request->session()->regenerateToken();
```
This change will keep it from breaking tests in downstream apps that have …
> Check for session before attempting to invalidate

- resources/views/components/button.blade.php
- resources/views/components/danger-button.blade.php
- resources/views/components/secondary-button.blade.php
- stubs/inertia/resources/js/Jetstream/Button.vue
- stubs/inertia/resources/js/Jetstream/DangerButton.vue
- stubs/inertia/resources/js/Jetstream/SecondaryButton.vue
- stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
- stubs/livewire/resources/views/teams/team-member-manager.blade.php
`shadow-outline` was [replaced](https://tailwindcss.com/docs/upgrading-to-v2#replace-shadow-outline-and-shadow-xs-with-ring-utilities) with `ring` in tailwind v2.
I used the ring colors that matched the colors from tailwind v1 the closest.
> [2.x] Replace shadow-outline with ring

- resources/views/components/modal.blade.php
Currently if there is any `<input type="hidden">` inside the modal, tabbing stops when that element is next.
This PR excludes such hidden inputs via the query-selector, so that focus progression is no longer stopped.
I couldn't find any existing tests for the modal or its tabbing in this repo, so I haven't updated or added any tests.
> [2.x] Exclude hidden inputs from focusable elements

- src/Http/Controllers/Inertia/ApiTokenController.php
- src/Http/Livewire/ApiTokenManager.php
Jetstream/Sanctum supports overwriting the PersonalAccessTokenModel via `Sanctum::$personalAccessTokenModel`
In the current state Jetstream will delete tokens via the query builder without fetching the token first, which will not trigger the deleting/deleted events.
There are some use-cases where you might want to "mirror" the changes to tokens to an API gateway.
> [2.x] Get model of PersonalAccessToken before deleting it to make sure the deleting/deleted events are triggered

- resources/views/components/modal.blade.php
`input:not([type=\'hidden\'])` Was missing the closing `)`. This causes the rest of the query to fail.
> [2.x] Fix selector query

- src/HasTeams.php
Fixes an error for null teams by adding a check to see if the team passed is null, and returns false instead of throwing an exception.
> Check OwnsTeam for null teams

- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
On inertia js stack, if jetstream profile photos feature is enabled then user selects a new photo and hits the save button several times without refreshing the page, the photo file input does not get cleared and inertia form would send the same file for each profile update post request via inertia post, also server would handle the file upload each time.
- Enable profile photos feature
- Visit the user profile page
- Select a new photo
- Click on the save button and do not refresh or navigate
- Save++
- Check form payload or users table profile_photo_path attribute or storage folder
- Visit user profile page
- Select a new photo
- Click save and do not refresh or navigate
- Click remove photo button and click save, the removed photo will reappear again.
> [2.x] Inertia - clear user profile photo input

- stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue
**Description**
While selecting a new profile photo, canceling the file selection window results in errors being displayed in the console saying,
`Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.`
[Video demonstration](https://streamable.com/ick9ee)
For some reason, the `@change="updatePhotoPreview"` method is being triggered although no changes were made to the input. Possibly a Vue related issue since this doesn't happen in the Livewire stack?
Probably worth noting that I've run into this issue on Windows and specifically Chromium based browsers.
**Steps to reproduce**
- Enable profile photos feature.
- Visit the user profile page.
- Select a new photo.
- Select a new photo again, only this time leave your selection empty and click cancel.
> [2.x] Inertia - ensure file selection is not empty before updating profile photo preview

- database/factories/TeamFactory.php
- database/factories/UserFactory.php
> Using faker method instead of properties

- stubs/inertia/resources/js/Pages/Profile/TwoFactorAuthenticationForm.vue
- stubs/livewire/resources/views/profile/two-factor-authentication-form.blade.php
This pull request removes dark classes from QR Code since Jetstream do not support dark mode.
> [2.x] Remove dark classes from QR Code

- database/migrations/2014_10_12_000000_create_users_table.php
As the TEXT type on some DBs, creates an column with a limit of 2/4 GB.
This should increase compatibly with other DBs, with no impact on the migration it self. But we DO limit the column length, which is a good thing for this column use case. As a good practice URI should not be longer then 2K.
There is no mention of max URI length in the RFC3986, but there are limitation imposed by the software like the browsers them self.
|DB        |typeString                                                                           |typeTinyText |typeText     |typeMediumText|typeLongText |
|----------|-------------------------------------------------------------------------------------|-------------|-------------|--------------|-------------|
|MySQL     |varchar({$column->length}) …
> [2.x] Changed the column type of profile_photo_path

- stubs/inertia/resources/views/app.blade.php
on inertia stack a when you run `npm install && npm run watch` if you work with `.test` domains like Laravel Valet add, the watcher does not add live reload with `browserSync` you must work with `localhost` ip to work with vue components.
to avoid this by adding this tag on `app.blade.php` file on inertia stack it would reload `.test` domains as it is a `localhost` domain.
it avoid confusion on why vue components does not reload using browserSync by default, and make easier the workflow with inertia and of course with jetstream.
> fix cors policy errors with inertia stack

- src/Role.php
I'm not sure whether this should be considered as a breaking change. But this will avoid loading translation early in the request lifecycle and instead only require it to be translated when returning a response.
> [2.x] Allow Role's `$name` and `$description` to be translated

- stubs/tests/RegistrationTest.php
Added checks to skip the tests if the registration support in Fortify is disabled, otherwise the tests fail.
> Skip registration tests if Fortify registration is disabled

- stubs/inertia/resources/js/Jetstream/Modal.vue
Remove the <body> overflow:hidden style when the modal component is unmounted.
Fixes #800
> Remove overflow property when unmounted

- resources/views/components/action-message.blade.php
- resources/views/components/dropdown.blade.php
- src/Console/InstallCommand.php
- stubs/livewire/resources/js/app.js
I've tested everything as best as I could in a brand new Jetstream install and everything seems to be working perfectly and exactly as it was on V2.
> Upgrade Alpine from V2 to V3

- stubs/inertia/tailwind.config.js
- stubs/livewire/tailwind.config.js
Tailwind offers a new just-in-time mode for Tailwind V2.1+. This feature is currently in preview, but I believe it is already productive in the current version. I suggest the use of Tailwind jit. It offers some very valuable advantages. See the further [documentation](https://tailwindcss.com/docs/just-in-time-mode)
> Tailwind JIT-Mode

- resources/views/components/action-message.blade.php
- resources/views/components/dropdown.blade.php
Problem scenario:
* Someone updates Jetstream to the latest version that supports Alpine V3
* They don't update their Alpine version to V3 (because package.json/app.js doesn't get automatically updated)
* Jetsream is now broken in the following two ways:
* The top right menu doesn't work because it uses `@click.outside` which is new in V3
* The little "Saved." indicator doesn't transition out because it uses `x-transition...` which is new in V3
Solution:
* Use `.away` instead of `.outside` - they are aliases and both exist in V2 and V3
* Include the legacy `x-show.transition...` as well as the new `x-transition...` helpers. Each will work on their respective versions without causing breakages.
After this PR, all Jetsream stubs will be upgrade safe and support any version of Alpine a …
> [2.x] Support both Alpine V2 and V3

- resources/views/components/modal.blade.php
This PR adds ability to use `focusable` attribute for focusing on first modal **_focusable_** element.
`<x-jet-dialog-modal wire:model="model" focusable>`
It's much faster, then tapping to first element on every modal open and makes user experience smoother and easier.
Otherwise, you can continue using current behaviour without breaking anything.
> [2.x] Add ability to focus first modal element on opening

- src/Http/Controllers/Inertia/CurrentUserController.php
- src/Http/Controllers/Inertia/OtherBrowserSessionsController.php
**Problem**: Password confirmation within Jetstream (Inertia) is not consistent. This breaks certain key features when using custom handling for confirming passwords e.g. when using a non-standard guard or user provider. 
- Password confirmation for enabling 2FA uses Fortify's `ConfirmPassword` action and can be customized by hooking into `confirmPasswordUsing`. This feature is working.
```
$confirmed = app(ConfirmPassword::class)(
$this->guard, $request->user(), $request->input('password')
);
```
- **Password confirmation for account deletion** and **signing out other browser sessions** use Laravel's password validation rule and can't be customized (easily). Password validation fails and these features don't work.
```
$request->validate([
'password' => 'required|string|password',
]);
``` …
> [2.x] Defer to Fortify for password confirmation

- composer.json
Fixes https://github.com/laravel/jetstream/issues/838
> [2.x] Fix commonmark install issue

- src/Http/Livewire/TeamMemberManager.php
Missing import from #837 PR
https://github.com/laravel/jetstream/blob/c343fb3e9b48ac2917c98297ec2ab87ee6d78e94/src/Http/Livewire/TeamMemberManager.php#L256-L260
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> Fixes missing import.

- composer.json
- src/Http/Controllers/Inertia/PrivacyPolicyController.php
- src/Http/Controllers/Inertia/TermsOfServiceController.php
- src/Http/Controllers/Livewire/PrivacyPolicyController.php
- src/Http/Controllers/Livewire/TermsOfServiceController.php
Use `Str::markdown` to support both CommonMark v1 and v2.
Fixes https://github.com/laravel/jetstream/issues/844
> [2.x] Support both CommonMark v1 & v2

- composer.json
#845 
Now we use Laravel's `\Str::markdown` instead of this dependency and we don't need it.
> remove unused dependency from composer.json

- src/Http/Controllers/Inertia/CurrentUserController.php
- src/Http/Controllers/Inertia/OtherBrowserSessionsController.php
Some strings in Inertia controllers were not translatable. This PR fixes this.
> make string constants a translation strings

- stubs/inertia/tailwind.config.js
- stubs/livewire/tailwind.config.js
Because of Tailwind JIT mode (#810), [defining extra variants in the config is not needed anymore](https://tailwindcss.com/docs/just-in-time-mode#all-variants-are-enabled).
> Remove unneeded tailwind config variant definitions

- README.md
Links were going to 1.x in the 2.x branch.
> Bumped doc links to v2 links in readme

- resources/views/components/banner.blade.php
Currently the banner component always show a success icon (`check-circle`) regardless of the style applied for the component.
~This PR simply changes this so that the current success icon (`check-circle`) is only used when the component style is `success` whereas a more neutral information icon (`exclamation-circle`) is used otherwise (meaning for `style='danger'` or any other custom styles added).~
This PR uses the `check-circle` icon for `style='success'`, the icon `exclamation-circle` for `style='danger'` and uses `information-cicle` as fallback for other styles + uses `bg-gray-500` for the topbar in this case (had no background before this PR).
> Update banner component svg icon

- stubs/app/Models/Team.php
- stubs/app/Models/TeamInvitation.php
- stubs/app/Models/User.php
- stubs/app/Models/UserWithTeams.php
Use PHPDoc comments from base class to stay consequent.
> [2.x] Use PHPDoc comments from base class in models

- src/Console/InstallCommand.php
Remove unnecessary `laravel/sanctum` from the installer command.
`laravel/sanctum` is already included since Laravel v8.6.0. see [Laravel v8.6.0](https://github.com/laravel/laravel/releases/tag/v8.6.0)
> [2.x] remove unnecessary composer package

- stubs/inertia/resources/views/app.blade.php
Including the `csrf_token` as a meta element conflicts with Inertia's built-in CSRF protection: https://inertiajs.com/csrf-protection#top
> Remove csrf_token from meta in Inertia app

- stubs/pest-tests/PasswordResetTest.php
- stubs/tests/PasswordResetTest.php
In the fortify routes file, all the routes being tested in both PHPUnit and Pest variants of `PasswordResetTest` are only exposed using the following condition (see [here](https://github.com/laravel/fortify/blob/a52a980b922694fbf7298ab70cc3da7fb716cfff/routes/routes.php#L45)):
```php
// Password Reset...
if (Features::enabled(Features::resetPasswords())) {
// ...
}
```
If the reset-passwords feature flag is disabled, this causes the published test files for `PasswordResetTest` to fail, regardless of the preferred testing framework used.
This PR updates both `PasswordResetTest` variants to use the correct feature flag, `Features::resetPasswords()` instead of `Features::updatePasswords()` which is currently being used incorrectly. 
I installed a fresh Laravel project with Jetstream using …
> [2.x] Use correct feature flag in password reset tests

- src/Http/Controllers/TeamInvitationController.php
Use the custom `TeamInvitation` class in the `accept` and `destroy` methods of the `TeamInvitationController` to retrieve the invitation model.
Fixes #890. 
Removes the type-hint from the controller methods. Therefore the model will not be resolved by the framework and the invitation id will be passed to the controller. Uses the invitation id and the Jetstream helper to query and retrieve an instance of the custom `TeamInvitation`. Uses `firstOrFail` as the route model binding responds with a `ModelNotFoundException` as well when an invalid id is passed.
> Use custom TeamInvitation model in TeamInvitationController

- stubs/inertia/resources/js/Jetstream/Dropdown.vue
Use KeyboardEvent `key` attribute for Escape instead of deprecated `keyCode`.
See https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
> Use KeyboardEvent `key` attribute for Escape

- src/HasTeams.php
Quick fix for #924, which I appreciate was closed, but since this is fixed in 2.x, thought maybe it could sneak through. 😅
> Correct PHP DocBlock reference

- stubs/inertia/tailwind.config.js
- stubs/livewire/tailwind.config.js
Since Jetstream is using TailwindCSS 3.x (#920) there aren't other modes than Just in Time supported anymore. 
The JIT mode is used by default.
So the mode:'jit' config entry can completely be  removed.
[Upgrade Guide for reference](https://tailwindcss.com/docs/upgrade-guide#migrating-to-the-jit-engine)
The config files should be clean and should not contain unnecessary entries.
> Remove JIT mode from tailwind config

- resources/views/components/dialog-modal.blade.php
- stubs/inertia/resources/js/Jetstream/DialogModal.vue
Fixed a button spacing issue in dialog modal footer.
> Fixed a button spacing issue in dialog modal footer.

- stubs/pest-tests/AuthenticationTest.php
Changes:
From:
- 'users can not authenticate with invalid_password'
To:
- 'users cannot authenticate with invalid password'
> Typo: Pest AuthenticationTest

- stubs/inertia/resources/js/Pages/Profile/Partials/LogoutOtherBrowserSessionsForm.vue
- stubs/livewire/resources/views/profile/logout-other-browser-sessions-form.blade.php
This pull request fixes an incorrect behavior of the 'Logout Other Browser Sessions' session list. If any of the browser's details are not matched in the jenssegers/agent library, currently it is displayed as 'false,' directly showing the output of the library which intentionally returns false if there is no match.
This pull request changes this to show as 'Unknown.' This seems a suitable term, as it is searching known browsers.
As requested in the contribution guide, I made this change in both Inertia and Livewire.
[Screenshot before](https://www.jonhassall.com/assets/2021/12/FalseSS.png)
[Screenshot after](https://www.jonhassall.com/assets/2021/12/FixedSS.png)
> Show 'Unknown' instead of 'false' if other browser session Useragent details are not matched in library

- stubs/tests/EmailVerificationTest.php
- stubs/tests/PasswordConfirmationTest.php
- stubs/tests/inertia/ApiTokenPermissionsTest.php
- stubs/tests/inertia/CreateApiTokenTest.php
- stubs/tests/inertia/DeleteApiTokenTest.php
- stubs/tests/livewire/ApiTokenPermissionsTest.php
- stubs/tests/livewire/CreateApiTokenTest.php
- stubs/tests/livewire/DeleteApiTokenTest.php
Because the user factory has intelligent team states, we can skip the teams feature check in the testsuite.
> Update test stubs

- routes/inertia.php
- routes/livewire.php
This addresses my issue in #956.
I believe there is a problem in the livewire and inertia route files with respect to using the default auth middleware instead of the auth:sanctum middleware which is used in the stubs for the dashboard route. This problem prevents me from using the new auth guard I've created to view the profile route because it does not respect the sanctum guard and there is no other way I see to change what guard this route group uses. I've tested this change and when implemented it allows me to correctly access the profile route as expected with my new auth guard.
I believe this could also be solved in a similar way to Fortify:
`
config('fortify.auth_middleware', 'auth').':'.config('fortify.guard')
`
but Jetstream doesn't seem to use the more complicated system so I …
> Route group Sanctum guard

- src/HasProfilePhoto.php
Laravel 9 uses Filesystem 3.
For deleting a file you must provide a string. But if no profile photo is set the profile_photo_path can be null.
This PR adds a Check before deleting the profile photo.
FilesystemAdapter Interface which requires the usage of a string:
https://github.com/thephpleague/flysystem/blob/912ba3e5595280999b9fa99a3c20c5ecb7de6870/src/FilesystemAdapter.php#L53
> Add Check before deleting a profile photo

- database/migrations/2014_10_12_000000_create_users_table.php
- database/migrations/2020_05_21_100000_create_teams_table.php
- database/migrations/2020_05_21_200000_create_team_user_table.php
- database/migrations/2020_05_21_300000_create_team_invitations_table.php
Hello,
this PR refactors all of the migrations to anonymous migrations.
Since the upcoming Laravel 9 release is pretty close maybe it is time to drop some old dependencies (Laravel 8 & PHP 7.x) in the Jetstream package and start doing changes for a next major Jetstream (3.x) version?
So this is a kind of a tryout pr. I just want to checkout how the future of Jetstream Open Source development will look like. And how these kind of PRs are received by the maintainers.
I'm not sure how the Jetstream Package Major Versions release cycle is going to look like in the future since this is the first Major Laravel Release after Jetstream was born  ( it really feels like a long time ago). 
I hope I'm not annoying anyone with this PR. Feel free to close this pr and thank you for your feedback!
Have a …
> Switch to Laravel 8.37 >= anonymous migrations

- src/Http/Middleware/ShareInertiaData.php
Hi there, this is my first laravel PR
The `$user->allTeams()` method returns a merged collection in the HasTeams trait with `$this->ownedTeams` and `$this->teams`.
Unfortunately eloquent `sortBy` method will re-index the keys out of order, so json encoding the output value of this method will convert it to a map in javascript rather than an array.
> Always return array to ui from allTeams()

- .github/workflows/tests.yml
- src/Role.php
- tests/JetstreamTest.php
Fixes https://github.com/laravel/jetstream/issues/968
I'm a bit baffled that I couldn't reproduce this. No matter what I tried I couldn't trigger the error they experiencing while clearly this indeed is an issue. There's something that's hard-suppressing deprecation notices but I don't know what...
> [8.x] Fix PHP 8.1 return type

- src/Console/InstallCommand.php
When I have multiple php versions, when trying to differentiate them using different aliases like `php`(7.1), `php74`, `php81`, now when I execute `php81 artisan jetstream:install livewire` in CLI , here will be unexpectedly fallback to `php`(7.1) execution, which will fail.
Now he will correctly get the `php81` I am using
I'm not sure how to write a test case for this modification, but it works for me, and I installed it by modifying the project's composer.json.
```json
"repositories": [
{
"type": "path",
"url": "C:\\web\\server\\laravel\\jetstream"
}
],
```
> Install command find the path to the php binary used

- stubs/tests/livewire/InviteTeamMemberTest.php
• Tests\Feature\InviteTeamMemberTest > team member invitations can be cancelled
Symfony\Component\Mime\Exception\LogicException 
An email must have a "From" or a "Sender" header.
at vendor/symfony/mime/Message.php:132
128▕             throw new LogicException('An email must have a "To", "Cc", or "Bcc" header.');
129▕         }
130▕ 
131▕         if (!$this->headers->has('From') && !$this->headers->has('Sender')) {
➜ 132▕             throw new LogicException('An email must have a "From" or a "Sender" header.');
133▕         }
134▕ 
135▕         parent::ensureValidity();
136▕     }
+11 vendor frames 
12  app/Actions/Jetstream/InviteTeamMember.php:39
Illuminate\Mail\PendingMail::send(Object(Laravel\Jetstream\Mail\TeamInvitation))
+32 vendor frames 
45 …
> [2.x] Mail Faker need on test cancelled invitations

- stubs/livewire/resources/views/navigation-menu.blade.php
This PR will switch the ```Log Out``` links in the Livewire navigation menu component from vanilla JS to Alpine's ```@click.prevent``` directive for a cleaner approach with the same result. Also, it should eliminate squawking from IDE's about using the ```event``` context when preventing the default action on clicking the links.
> Use Alpine's @click.prevent for log out

- src/HasTeams.php
Just a small tweak, not a functional one. Would call for `teams` after checks for ownership.
This should not break anything.
> [2.x] First check for ownership

- composer.json
- src/Http/Controllers/Inertia/Concerns/ConfirmsTwoFactorAuthentication.php
- src/Http/Controllers/Inertia/UserProfileController.php
- src/Http/Livewire/TwoFactorAuthenticationForm.php
- stubs/inertia/resources/js/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue
- stubs/inertia/resources/js/Pages/Profile/Show.vue
- stubs/livewire/resources/views/profile/two-factor-authentication-form.blade.php
- tests/UserProfileControllerTest.php
This PR implements the Jetstream side of things to confirm 2FA when enabling it. This prevents the user from accidentally enabling 2FA and locking themselves out of their account.
Related Fortify PR: https://github.com/laravel/fortify/pull/358
Todo:
Closes https://github.com/laravel/jetstream/issues/74
> [2.x] Confirm 2FA when enabling

- src/HasProfilePhoto.php
In order to use the hasProfilePhoto Trait on other Models i added a second parameter to set the storage path for the model. With this you can store profile photos for teams in a different folder as user profile photos. 
This time in the correct branch.
> Adding Storage Path support to the HasProfilePhoto Trait

- stubs/inertia/webpack.config.js
- stubs/inertia/webpack.mix.js
This PR removes the `webpack.config.js` file in order to use the `alias` method from `Mix`.
> Use `.alias` method from `Mix`

- src/Console/InstallCommand.php
Missed from https://github.com/laravel/jetstream/pull/1009.
There will be no `webpack.config.js` file.
Thanks
> Remove missing `webpack.config.js` from the installer

- src/Console/InstallCommand.php
- src/Http/Middleware/ShareInertiaData.php
- stubs/inertia/resources/js/ssr.js
- stubs/inertia/resources/views/app.blade.php
- stubs/inertia/webpack.ssr.mix.js
This PR adds the SSR support for the Inertia stack.
To not be a default option, I added a `--ssr` option, this way we will only include the SSR part if the user wants.
to have the SSR running make sure to run:
```sh
npm run prod
```
then to start the ssr server run:
```sh
node public/js/ssr.js
```
More information on the Inertia website: https://inertiajs.com/server-side-rendering
The directive `@inertiaHead` added to the `app.blade.php` will not do anything if the SSR is not enabled.
> [2.x] Add Inertia SSR Support

- stubs/inertia/resources/js/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue
- stubs/livewire/resources/views/profile/two-factor-authentication-form.blade.php
* Allow user to enter setup key in authenticator apps if they can't scan the QR code
The inertia side relies on the matching fortify pull request: https://github.com/laravel/fortify/pull/371
> 2FA Setup Key

- src/Console/InstallCommand.php
- src/Http/Middleware/ShareInertiaData.php
- stubs/inertia/app/Http/Middleware/HandleInertiaRequests.php
This PR fixes #1023
Removes the addition of `Ziggy` on the `ShareInertiaData` middleware, and only add `Ziggy` to the `HandleInertiaData` stub if `--ssr` is passed, so that way if anyone wants to remove, they have the full control.
Thanks,
Francisco
> [2.x] Not require `Ziggy` on `ShareInertiaData` middleware.

- resources/views/components/switchable-team.blade.php
This PR will switch the `switchable-team` component in the Livewire stack from vanilla JS to Alpine's `@click.prevent` directive, like my previous PR #989 for the log out link.
> Use Alpine's @click.prevent for switching teams

- src/Http/Controllers/Inertia/Concerns/ConfirmsTwoFactorAuthentication.php
- stubs/inertia/resources/js/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue
This PR fixes the error handling during 2FA confirmation for the Inertia Stack. The Livewire Stack already works as expected. 
- the error message for an invalid confirmation code will be correctly read from the form error bag, see [Fortify counterpart](https://github.com/laravel/fortify/blob/1.x/src/Actions/ConfirmTwoFactorAuthentication.php#L43)
- texts and buttons refresh accordingly to the current confirmation state
- confirmation form resets when 2FA process
- adds an additional check to determine if the confirmation process finished
Fixes #1028
> [2.x] Fix error handling during 2FA confirmation

- stubs/inertia/resources/js/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue
This PR fixes the error when logging out when the TwoFactorAuthenticationForm component is loaded and the watcher is working.
Fixes or is a follow up on https://github.com/laravel/jetstream/issues/1030
> [2.x] Fix: if user logs out when viewing the 2FA Form

- src/Console/InstallCommand.php
This PR adds the functionality to install pest as a dev dependency when installing jeststream with the `--pest` flag.
> [2.x] Install pest as devDependency

- stubs/inertia/resources/js/app.js
- stubs/livewire/resources/js/app.js
Carrying on from the PR at https://github.com/laravel/laravel/pull/5895, this replaces `require` statements with `import` statements where possible in the JS resources in order to smooth the transition for Vite users.
Note that with Inertia there is one remaining dynamic `require` that does not have a replacement that works with webpack _and_ Vite.
> [2.x] Switch to ESM imports

- src/Console/InstallCommand.php
This is to make it on par with the Jetstream stack as well as remove the current compilation warnings.
> Bump tailwindcss/forms to 0.5.0

- src/Console/InstallCommand.php
- stubs/inertia/webpack.mix.js
- stubs/livewire/webpack.mix.js
- stubs/resources/css/app.css
This PR simplifies the Tailwind installation in Jetstream and is the counterpart of [this Breeze PR](https://github.com/laravel/breeze/pull/155):
* Uses the `@tailwind` directive instead of `@import`, per the standard [installation guide](https://tailwindcss.com/docs/guides/laravel).
* Removes the unnecessary `postcss-import` dependency and Mix configuration.
> [2.x] Simplify Tailwind installation

- stubs/inertia/resources/js/Pages/Teams/Partials/UpdateTeamNameForm.vue
This adds the .vue extension to match all other Vue files in the repository. 
It also plays nice with Vite.
> Add .vue extension to imports

- src/Console/InstallCommand.php
- stubs/inertia/tailwind.config.js
- stubs/livewire/tailwind.config.js
Hey Laravel Team,
this PR updates TailwindCSS to the new 3.1 release and adds the new FirstParty TypeScript types to the tailwind.config.js.
https://tailwindcss.com/blog/tailwindcss-v3-1
> Bump TailwindCSS to 3.1

- stubs/inertia/resources/js/app.js
- stubs/inertia/resources/js/ssr.js
- stubs/inertia/webpack.mix.js
- stubs/inertia/webpack.ssr.mix.js
This PR fixes an error where the Ziggy `route()` helper is undefined when `route()` is used in the `setup()` function and Inertia SSR is being used. 
1. Install Jetstream with Inertia SSR `php artisan jetstream:install inertia --ssr`
2. In the `Welcome.vue` file, for example, use the route function inside `<script setup>`:
```js
const test = route('login')
```
3. Display the result in the template somewhere:
` {{ test }}`
4. Compile ssr.js `npx mix --mix-config=webpack.ssr.mix.js`
5. Compile app.js `npm run dev`
6. Start the SSR service `node public/js/ssr.js`
7. Upon visiting the page, there will be an error in the node terminal (and the page will fall back to client-side rendering):
`ReferenceError: route is not defined`
Using `route()` in the setup function will work using client-side …
> [2.x] Fix Inertia SSR usage with Ziggy route function in setup()

- stubs/inertia/tailwind.config.js
- stubs/livewire/tailwind.config.js
This PR fixes the new TailwindCSS 3.1 First-party TypeScript types feature.
This Bug was introduced with.
https://github.com/laravel/jetstream/pull/1066
Thanks to @martinvadel who recognized it.
> fix TailwindCSS first party TypeScript types weren't working right

- src/Console/InstallCommand.php
Although not technically necessary as the version constraints allows for the latest `0.5.2` version and the latest allowed version would be installed on `npm install`, sending this PR through to match the `laravel/breeze` PR / versioning which we also bumped to this version to avoid a Vite console warning.
See: https://github.com/laravel/breeze/pull/161
> bump @tailwindcss/forms

- src/Http/Middleware/ShareInertiaData.php
- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/inertia/resources/js/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue
- stubs/inertia/resources/js/Pages/Profile/Show.vue
- stubs/inertia/resources/js/Pages/Teams/Partials/CreateTeamForm.vue
- stubs/inertia/resources/js/Pages/Teams/Partials/TeamMemberManager.vue
- stubs/inertia/resources/js/Pages/Welcome.vue
This PR is proposed to nest the shared user prop under auth key as proposed in #323.
Since this is a breaking change, am targeting the next major release https://github.com/laravel/jetstream/pull/323#issuecomment-1162846960.
If approved, the docs and upgrade guide will also need to be updated.
No hard feelings on closure
> [3.x] Change $page.user to $page.auth.user

- stubs/inertia/app/Http/Middleware/HandleInertiaRequests.php
- stubs/inertia/resources/js/ssr.js
I've noticed that using the URL property to handle the active route on Ziggy in SSR is not correct. Indeed, we need to know the current URL and the URL property returns the base URL of the application.
To reproduce the bug, just disable the JS and find that the active route in the menu does not work. With JS, it works because the client re-hydrates the server-generated DOM.
So, I think we need to get current URL via request and totally replace window.location so.
> Fix ziggy location instead of base url

- stubs/inertia/vite.config.js
- stubs/livewire/vite.config.js
This PR makes both the jetstream stacks come with the default Laravel watching configuration out of the box.
As it stands, this will perform a full page refresh while running `npm run dev` and saving files within the following directories:
```
resources/views/**
routes/**
```
The configured directories can still be manually configured if needed.
Tested stacks:
- Inertia
- Inertia --ssr
- Livewire
See: https://github.com/laravel/vite-plugin/pull/43
> [2.x] Add default view / routes reloading to jetstream stacks

- .github/workflows/tests.yml
- composer.json
Dropping Laravel 8.x support as:
- Jetstream is only meant to be installed on ["new applications"](https://jetstream.laravel.com/2.x/installation.html). I interpret this as meaning `composer create-project laravel/laravel app`.
Adding conflict as:
- Vite is only supported in `laravel/framework:^9.19.0`.
Dropping support for PHP < 8.0.2 as:
- The current version of Laravel 9.x only supports `PHP:^8.0.2`.
I'm also not sure how Laravel approaches dropping version support with SemVer - especially when it comes to these started kits. I'm pretty sure dropping version support is not a "breaking change" in SemVer world.
Alternatively, we could back port Vite but this would probably also include ongoing feature improvements in `laravel/framework` around Vite as well.
Testing script:
```sh
composer …
```
> [2.x] Drop Laravel 8.x support (and PHP < 8)

- src/Console/InstallCommand.php
This PR updates the `.gitignore` entry that we add for the SSR build directory to use the new location from https://github.com/laravel/vite-plugin/pull/70.
We should hold off releasing this until the new version of `laravel-vite-plugin` has also been released.
> [2.x] Update SSR directory

- stubs/livewire/vite.config.js
This is dependent on merging and tagging of: 
- ~https://github.com/laravel/vite-plugin/pull/55~
- https://github.com/laravel/laravel/pull/5932
so the tests are currently failing, however this has been tested locally.
This PR additionally watches `app/Http/Livewire/**` in the Livewire stack, as "inline" components contain all their view logic there. When files there change, the browser will perform a full page refresh.
Test script...
```
composer create-project laravel/laravel:9.x-dev jetstream-test \
&& cd jetstream-test \
&& composer require laravel/jetstream:livewire-refresh-dev \
&& php artisan jetstream:install livewire \
&& sed -i "s/SESSION_DRIVER=database/SESSION_DRIVER=file/" .env \
&& npm install \
&& npm run dev
php artisan serve
php artisan make:livewire Counter --inline
``` …
> [2.x] Add livewire component paths to default refresh paths for livewire stack

- stubs/livewire/resources/views/layouts/app.blade.php
Changed the position where the Livewire styles got loaded, from before, to after the Vite injection.
This is to prevent missleading behaivor of Livewire as discussed in the Livewire Discord:
> Change position of Livewire Style

- stubs/pest-tests/inertia/TwoFactorAuthenticationSettingsTest.php
- stubs/pest-tests/livewire/TwoFactorAuthenticationSettingsTest.php
- stubs/tests/inertia/TwoFactorAuthenticationSettingsTest.php
- stubs/tests/livewire/TwoFactorAuthenticationSettingsTest.php
On a fresh install, many of the test stubs include checks for disabled features and those tests are skipped when appropriate.  This isn't the case for the two factor authentication feature tests, so I propose adding those feature checks to the test stubs.
I realize this was suggested in #793 last year but IMO the two factor authentication checks not having these checks while the others do is an inconsistent behavior and it can be somewhat surprising to see failures for a disabled feature because of the missing checks.
> Skip two factor authentication tests when the feature is disabled

- src/Console/InstallCommand.php
This PR changes `Please execute the [npm install && npm run dev] commands to build your assets.`
to `Please execute the [npm install && npm run build] commands to build your assets.` to reflect the move to vite.
> Update install command output to display vite build command

- src/Console/InstallCommand.php
Currently when running `jetstream:install`, if you specify an invalid stack such as "vue", you'll end up with a partial Jetstream install and no error message.
This PR validates that the stack is either `inertia` or `livewire`.
Note that there is no default stack in Jetstream and it already displays an error when the stack is not provided.
Ultimately I'd love to prompt the user if they don't specify a stack, but that raises bigger questions of whether it should prompt for options like `teams` etc.
> Validate the stack argument

- src/Console/InstallCommand.php
Currently when running `jetstream:install`, if you specify an invalid stack such as "vue", you'll end up with a partial Jetstream install and no error message.
This PR validates that the stack is either `inertia` or `livewire`.
Note that there is no default stack in Jetstream and it already displays an error when the stack is not provided.
Ultimately I'd love to prompt the user if they don't specify a stack, but that raises bigger questions of whether it should prompt for options like `teams` etc.
> [2.x] Validate the stack argument

- src/Console/InstallCommand.php
This PR updates the Jetstream installer to automatically run the `npm install` and `npm run build` commands for you.
Currently, the [Laravel installer](https://github.com/laravel/installer/blob/df70a9391dbd5f911565312f8afc125a5e86e0d9/src/NewCommand.php#L173) automatically runs these commands when it installs Jetstream. Moving it to this package makes the installation more consistent no matter how you install it. I have created https://github.com/laravel/installer/pull/242 to remove these from the Laravel installer.
> [2.x] Install NPM dependencies and build assets

- composer.json
- src/Console/InstallCommand.php
This updates the Inertia Laravel Adapter to ^0.6.3. The main reason for this is that this release contains logic to utilise the Vite Manifest when cache busting.
https://github.com/inertiajs/inertia-laravel/releases/tag/v0.6.3
With Jetstream now using Vite as the default, I think it makes sense to include the latest version of the Laravel adapter so that no user changes are required to get `HandleInertiaRequests::version` working correctly.
https://github.com/laravel/jetstream/blob/2.x/stubs/inertia/app/Http/Middleware/HandleInertiaRequests.php#L24
> [2.x ] Update inertiajs/inertia-laravel to ^0.6.3

- src/Http/Middleware/ShareInertiaData.php
- src/Jetstream.php
- tests/Fixtures/Admin.php
- tests/JetstreamTest.php
- tests/OrchestraTestCase.php
This would be useful for applications with multiple user providers and uses Inertia (as `ShareInertiaData` middleware is appended to global web middleware). As an example, this will fix laravel/nova-issues#4683
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> Check current model supports HasTeams before trying to access team information.

- stubs/pest-tests/livewire/BrowserSessionsTest.php
- stubs/tests/livewire/BrowserSessionsTest.php
This test was not performing any assertion. See https://github.com/laravel/jetstream/issues/1137
> [2.x] Fix test

- stubs/livewire/resources/views/auth/register.blade.php
livewire was missed in #1127
required has been added to inertia, do the same for livewire
the error message is already present
> Register: add required to terms checkbox

- stubs/livewire/resources/views/profile/logout-other-browser-sessions-form.blade.php
Added missing localization for `Unknown` in [logout-other-browser-sessions-form.blade.php](https://github.com/laravel/jetstream/blob/bb406d8a827b66e372546f2dbc9ce4465609cfa5/stubs/livewire/resources/views/profile/logout-other-browser-sessions-form.blade.php)
> Added missing localization in logout-other-browser-sessions-form.blade.php

- database/factories/UserFactory.php
Jetstream creates migrations to add new columns in the user table, even if Jetstream isn't configured to use teams or profile pictures or 2FA. But because these fields are missing from the `UserFactory` that Jetstream installs, the default Jetstream tests will fail when using the `Model::preventAccessingMissingAttributes()` feature of model strictness.
These test failures are extremely unexpected when you've followed the happy path of Laravel, Jetstream, and then merely enabled model strictness. And the failures are not obvious. People who are new to Laravel seem likely to be very confused by these errors and might be dissuaded from using model strictness (and I do think people should be **encouraged** to use model strictness).
Adding these missing fields to the factory prevents these …
> Include all user table columns in the UserFactory

- resources/views/components/banner.blade.php
- resources/views/components/confirmation-modal.blade.php
- resources/views/components/switchable-team.blade.php
- resources/views/components/welcome.blade.php
- stubs/inertia/resources/js/Components/Banner.vue
- stubs/inertia/resources/js/Components/ConfirmationModal.vue
- stubs/inertia/resources/js/Components/Welcome.vue
- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/inertia/resources/js/Pages/Profile/Partials/LogoutOtherBrowserSessionsForm.vue
- stubs/inertia/resources/js/Pages/Teams/Partials/TeamMemberManager.vue
- stubs/inertia/resources/js/Pages/Welcome.vue
- stubs/livewire/resources/views/navigation-menu.blade.php
- stubs/livewire/resources/views/profile/logout-other-browser-sessions-form.blade.php
- stubs/livewire/resources/views/teams/team-member-manager.blade.php
Updates all icons to the new Heroicons v2
> Update to Heroicons v2

- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/livewire/resources/views/navigation-menu.blade.php
This change adds a focus style to **Settings Dropdown** trigger button in a similar manner to the **Teams Dropdown.**
The following screenshots show the focused state of the buttons before and after.
**P.S**: I have bumped up the background color of the buttons in the screenshot for the sake of contrast.
**Before**
**After**
> add focus styling for settings dropdown trigger button

- stubs/inertia/resources/js/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue
Attribute "v-if" should go before "class" to keep the same style than are using the other elements.
> Fix the order of the v-if attribute.

- src/JetstreamServiceProvider.php
When publishing Inertia assets (`artisan vendor:publish --provider=Laravel\\Jetstream\\JetstreamServiceProvider`, `artisan vendor:publish --tag=jetstream-inertia-auth-pages`, etc), you're presented with an error that some of the paths related to `jetstream-inertia-auth-pages` can't be located.
This is because Jetstream v2.11.0 (more specifically PR #1110) moved the Vue component stubs from `stubs/inertia/resources/js/Jetstream` to `stubs/inertia/resources/js/Components`.
I adjusted those paths in the service provider that registers the publishables.
I also removed the publishing of `stubs/inertia/resources/js/Components/ValidationErrors.vue` entirely, as that component was removed in v2.11.1 (PR #1123).
The Jetstream installation command was already publishing everything correctly.
I've …
> Fixes publishing jetstream-inertia-auth-pages, that was referencing an old stub path

- database/factories/UserFactory.php
- tests/OrchestraTestCase.php
- tests/UserProfileControllerTest.php
Fixes #1164
This is a resubmit of #1168 which was reverted in #1170 due to failing tests. The tests were failing because the `two_factor_*` columns are added by a Fortify migration which was not being run. I have solved this by configuring the Fortify migrations to run during testing. This has the nice side-effect of allowing us to remove manual migration code from one of the tests :tada:
> [2.x] Prevent `MissingAttributeException`

- src/Console/InstallCommand.php
Jetstream has a welcome page and a welcome component. The previous implementation was excluding both when stripping dark classes, but it should only exclude the welcome page so that the welcome component does not end up with dark classes.
Fixes #1223
> [2.x] Strip dark classes from welcome component when dark mode isn't selected.

- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/livewire/resources/views/navigation-menu.blade.php
Currently the dark dropdown text is gray-500 compared to nav-links which have text of gray-400.
This PR aims to make the nav menu items consistent.
> Update nav menu dark text to be consistent with nav link

- src/Http/Livewire/DeleteUserForm.php
@riasvdv introduced the ability to redirect to a configurable route using [laravel/fortify](https://github.com/laravel/fortify)'s config (`fortify.redirects.logout`) once the user has been deleted in commit dfc3ffcf490ecf799d54105bd1fae84606d6a947.
The problem here is that even though `fortify.redirects.logout` is `null`, it will not use the default value (`/`) unless the config key doesn't exist at all. Therefore, `return redirect(config('fortify.redirects.logout', '/'));` will return `null` and not redirect the user.
I've replaced the default value with a null coalescing operator so that if `fortify.redirects.logout` is `null`, it will redirect to `/`.
> Fixed not redirecting after deleting the user

- src/HasProfilePhoto.php
- src/Http/Livewire/DeleteUserForm.php
This will convert the profile photo attribute in ```HasProfilePhoto.php``` to the newer Attribute syntax from Laravel 9. While the function name reads cleaner, the only tradeoff is that it does add a few lines to the file.
This shouldn't be a breaking change since the attribute will still be accessible as ```profile_photo_url``` to both Livewire and Inertia. Also, the composer.json on the 2.x branch points to Laravel 9 and 10; so, it won't affect anyone using Jetstream with Laravel 8.
> [2.x] Convert Profile Photo URL attribute to newer syntax

- resources/views/components/confirms-password.blade.php
- stubs/inertia/resources/js/Components/ConfirmsPassword.vue
- stubs/inertia/resources/js/Pages/Auth/ForgotPassword.vue
- stubs/inertia/resources/js/Pages/Auth/Login.vue
- stubs/inertia/resources/js/Pages/Auth/Register.vue
- stubs/inertia/resources/js/Pages/Auth/ResetPassword.vue
- stubs/inertia/resources/js/Pages/Profile/Partials/DeleteUserForm.vue
- stubs/inertia/resources/js/Pages/Profile/Partials/LogoutOtherBrowserSessionsForm.vue
- stubs/inertia/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
- stubs/livewire/resources/views/auth/forgot-password.blade.php
- stubs/livewire/resources/views/auth/login.blade.php
- stubs/livewire/resources/views/auth/register.blade.php
- stubs/livewire/resources/views/auth/reset-password.blade.php
- stubs/livewire/resources/views/profile/delete-user-form.blade.php
- stubs/livewire/resources/views/profile/logout-other-browser-sessions-form.blade.php
- stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
Fixing autocomplete attributes here as requested by @driesvints 
Related PR: https://github.com/laravel/breeze/pull/245
> [2.x] Use autocomplete for all fields for password manager compatibility

- src/Console/InstallCommand.php
This pull request fixes a regression introduced by https://github.com/laravel/jetstream/pull/1216/files, where a few Pest stub files, such as `tests/Pest.php` were not being copied.
> [2.x] Fixes Pest stubs files

- .github/workflows/tests.yml
Removes the `--verbose` PHPUnit option used in CI as this is no longer available when running the workflow against Laravel 10.x.
I noticed my scheduled CI workflows failing because of this on Socialstream, because of `composer create-project laravel/laravel:10.x-dev` in the `Setup Laravel` step in my CI pipeline.
As of PHPUnit 10.0, the `--verbose` option no longer exists (see related issue [here](https://github.com/sebastianbergmann/phpunit/issues/4956)) and since Laravel 10.x requires a PHPUnit version `^10.0`, this will also cause the `Execute tests` step to fail in Jetstream.
> Removes `--verbose` PHPUnit option from tests workflow.

- stubs/inertia/resources/js/Pages/Welcome.vue
This PR updates the text on the Vue "welcome" page to match the change to the skeleton from https://github.com/laravel/laravel/pull/6099
> [3.x] Update welcome text

- stubs/inertia/resources/js/Components/Welcome.vue
The classes for the mentioned link seem to have been reversed with the classes from the svg file.
This pull request fixes the link to the correct layout while still supporting dark mode.
> Fixes incorrect classes for Laracasts link on Welcome.vue component.

- .github/workflows/tests.yml
This PR updates the `Test Stubs` CI pipeline for Jetstream to ensure backwards compatibility with Laravel ^9.21, as per the `composer.json` minimum requirements.
> [3.x] Ensure CI considers backwards compatibility with Laravel 9

- .github/workflows/tests.yml
Reverts laravel/jetstream#1258 as it's not needed. Just testing the latest versions is fine.
> Revert "[3.x] Ensure CI considers backwards compatibility with Laravel 9"

- database/factories/UserFactory.php
Based on https://github.com/laravel/laravel/pull/6119, this pull request removes `@return $this` when returning static.
> [3.x] Removes `@return $this` when returning static

- UPGRADE.md
Found a typo in the upgrade guide "userPage" that should be "usePage".
> Fixes typo from userPage to usePage

- database/factories/UserFactory.php
* User Factory in the database/factories folder, specifically the `withPersonalTeam` method, now has a callable parameter that will apply to the factory.
Allows for modification of the withPersonalTeam method so that a callable can be passed to the method to modify the team factory further, for example:
```php
User::factory()->withPersonalTeam(
fn (TeamFactory $factory) => $factory
->state([
'foo' => 'bar',
])
->has(
Post::factory()
->count(10)
)
)
->create();
```
I find myself wanting this out of the box when I use Jetstream, and others would appreciate the ability to do it without copying it to their project every time. Equally, it doesn't break any compatibility.
> [3.x] allow modification of the personal team using an optional callable

- stubs/pest-tests/livewire/TwoFactorAuthenticationSettingsTest.php
In my installation, these tests fail because the user doesn't have the `two_factor_confirmed_at` attribute:
```
The attribute [two_factor_confirmed_at] either does not exist or was not retrieved for model [App\Models\User]. (View: /var/www/html/vendor/livewire/livewire/src/views/mount-component.blade.php)
```
I believe this is because the factory doesn't specify the attribute.
I considered updating the factory to include it (set to `null`), but then I thought it might be a little messy because there should be a check to see if the feature's enabled.
This solution, however, requires everyone to remember to get a fresh user instance, when needed, without it being clear as to why.
So...let me know if I should try a different approach...
> Get fresh user instance on two factor authentication tests

- stubs/livewire/resources/views/auth/two-factor-challenge.blade.php
- stubs/resources/css/app.css
The following pull request fixes the issue as explained here: https://github.com/laravel/jetstream/issues/1289#issue-1652817995
Reloading/refreshing the page no longer causes the recovery code form input to appear for a short amount of time. The "blip" as Alpine calls it is no longer occuring, which was causing the issue in the first place. 
In Alpine's documentation:
"_Sometimes, when you're using AlpineJS for a part of your template, there is a "blip" where you might see your uninitialized template after the page loads, but before Alpine loads._"
"_`x-cloak` addresses this scenario by hiding the element it's attached to until Alpine is fully loaded on the page._"
> Fix issue with page reload/refresh on two-factor-challenge page

- stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
Hi, I've noticed that there is a `v-show` directive used on a div in the Livewire-powered `update-profile-information-form` Blade template, which is also wrapped into a `@if` statement. I'd assume it's the one or the other, in this case, without it.
> [3.x] Remove `v-show` directive from "user profile information form" template

- stubs/inertia/resources/js/Layouts/AppLayout.vue
- stubs/livewire/resources/views/navigation-menu.blade.php
Add logic to only display the "Switch Teams" options if the authenticated user belongs to more than 1 team. Previous to this change, if additional teams were not created and the user only had their personal team, the user was shown a nonfunctional option to "change" to the already active team.
> Only show "Change Teams" options if multiple teams are available

- src/HasProfilePhoto.php
- src/Http/Controllers/Inertia/TeamController.php
- src/Http/Controllers/Inertia/UserProfileController.php
- src/JetstreamServiceProvider.php
- tests/Fixtures/Admin.php
- tests/HasTeamsTest.php
- tests/JetstreamTest.php
- tests/OrchestraTestCase.php
Removing unused imports, checked using `laravel/pint`.
> remove unused imports

- stubs/inertia/resources/js/Pages/Teams/Partials/TeamMemberManager.vue
- stubs/livewire/resources/views/teams/team-member-manager.blade.php
This class is used elsewhere in the code where the user profile photo is displayed, so the purpose of this change (adding `object-cover`  class) is to maintain style consistency in displaying the profile photo.
https://github.com/laravel/jetstream/blob/802e9c43bbeb8ed933000689c2e4f99866ebbb71/stubs/inertia/resources/js/Layouts/AppLayout.vue#L123
https://github.com/laravel/jetstream/blob/802e9c43bbeb8ed933000689c2e4f99866ebbb71/stubs/inertia/resources/js/Layouts/AppLayout.vue#L205
https://github.com/laravel/jetstream/blob/802e9c43bbeb8ed933000689c2e4f99866ebbb71/stubs/inertia/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue#L103
https://github.com/laravel/jetstream/blob/802e9c43bbeb8ed933000689c2e4f99866ebbb71/stubs/inertia/resources/js/Pages/Teams/Partials/CreateTeamFor …
> Add object-cover class to team member profile photo

- stubs/inertia/postcss.config.js
- stubs/inertia/tailwind.config.js
- stubs/livewire/postcss.config.js
- stubs/livewire/tailwind.config.js
Full description: https://github.com/laravel/vite-plugin/pull/189
See:
- https://github.com/laravel/vite-plugin/pull/189
- https://github.com/laravel/laravel/pull/6090
- https://github.com/laravel/breeze/pull/246
> **Note** This will fail until the skeleton is tagged.
> [2.x] Migrate to modules

- src/Http/Livewire/UpdateProfileInformationForm.php
If email is hidden for serialization (in the User model `hidden` array) the view will crash, as `toArray()` won't include the email.
Hiding email field in particular is useful to avoid accidentally exposing other users emails to the frontend / client.
> Ensure email is included in state

- src/Console/InstallCommand.php
- stubs/inertia/jsconfig.json
It copies jsconfig.json file which is helpful for popular IDEs to base path.
> [3.x] jsconfig.json configuration file

- stubs/inertia/resources/js/app.js
- stubs/inertia/resources/js/ssr.js
Currently, appName in app.tsx is pulled via DOM from app.blade.php <title> tag. It works, but using it from .env seems like a better approach. Additionally, it serves as an example of how .env variables should be accessed in React/Vue.
The ssr template had 'Laravel' hardcoded as the app name, which is not great for SEO. Replaced that part with import.meta.env.VITE_APP_NAME as well.
This depends on https://github.com/laravel/laravel/pull/6204 where I added VITE_APP_NAME as an alias to APP_NAME
I don't think any changes in this PR could be considered breaking.
Similar issue fixed in Breeze: https://github.com/laravel/breeze/pull/292
> Use appName directly from .env in <title>

- stubs/inertia/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
- stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
The controller validation has it as required. This change reflects that in the frontend.
https://github.com/laravel/jetstream/blob/e9a3879058bce5a4d25b6b2e7b70c961d7909c75/stubs/app/Actions/Fortify/UpdateUserProfileInformation.php#L20-L22
Avoids waiting for the server to show the error to the user and helps with accessibility by informing a priori of the requirement.
> set email as required in input for UpdateUserProfileInformation

- stubs/inertia/resources/js/app.js
Using the additional `Ziggy` parameter with `.use(ZiggyVue, Ziggy)` is unnecessary when using the `@routes` Blade directive. Leaving this in (accurately) triggers an ESLint error `ESLint: 'Ziggy' is not defined.(no-undef)` since `Ziggy` is undefined in this context.
Since this additional parameter isn't necessary as the `@routes` blade directive is already being used, it should be removed to avoid triggering errors when using ESLint.
Alternatively, we could add `const { Ziggy } = window` or change the parameter to `window.Ziggy`, but this is all unnecessary and removing it seems to be the simplest, cleanest solution.
See [Ziggy Docs]( https://github.com/tighten/ziggy#vue) for more information
> Note: If you use the @routes Blade directive in your views, Ziggy's configuration will already …
> [3.x] Remove unnecessary Ziggy parameter which causes ESLint errors

- src/JetstreamServiceProvider.php
> [3.x] Use available `ServiceProvider::callAfterResolving()`

- stubs/inertia/resources/js/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue
Adding `dark:text-gray-100` on recovery codes.
> Make recovery code light when it on dark mode

- stubs/inertia/resources/js/Components/Banner.vue
This alters already accepted PR https://github.com/laravel/jetstream/pull/1045 to trigger the banner even if the next message contents did not change.
Explanation:
`watch`: setting the same value for a primitive type (number, string, boolean...) will not be considered as a value change.
`watchEffect`: triggers the change even if you set the same value, showing the banner again.
How to reproduce:
1. Flash a banner with the message "Action successful."
2. The user acknowledges the banner and clicks on the x button.
3. Flash another banner with the same message "Action successful."
4. No banners will be shown again, unless the message contents changes, user manually reloads the page or does a non-Inertia navigation.
> Fix the banner not showing again after dismissed by the user if the next message contents are the same

- stubs/inertia/resources/js/Components/Banner.vue
- stubs/inertia/resources/js/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue
- stubs/inertia/resources/js/Pages/Teams/Partials/TeamMemberManager.vue
This PR fixes a memory leak and potential caching issue in the Vue stack when calling `usePage` inside a computed prop or watcher.
`usePage` should be called at the top level of `<script setup>` per the example in the docs at https://inertiajs.com/shared-data#accessing-shared-data.
See https://github.com/inertiajs/inertia/issues/1602#issuecomment-1654815969 for more information.
> [3.x] Fix memory leak and potential caching issue with usePage

- src/Console/InstallCommand.php
This PR removes the check for an existing session table migration, as it does not work with anonymous migrations.
Rather than try to implement new detection logic here, I've created https://github.com/laravel/framework/pull/48602 to handle this directly in the `session:table` command.
Fixes #1384
> [4.x] Remove outdated session migration check

- src/JetstreamServiceProvider.php
REF: https://github.com/livewire/livewire/pull/7076#issuecomment-1768027945
REF: https://github.com/livewire/livewire/discussions/7093
In the latest release of [Livewire v3.0.9](https://github.com/livewire/livewire/tree/v3.0.9), Laravel Service Container is utilized for Dependency Resolution, which after testing with a new installation of Jetstream found to have a premature component registration due to a race condition, resulting in `Unable to find component: [navigation-menu]` exceptions.
**Explaination:**
- Previously, mechanisms were created using standard PHP object creation `(new $mechanism)`, not involving Laravel's service container, hence no service container events were triggered. `LivewireServiceProvider::registerMechanisms()`
- With the recent change, these mechanisms are now …
> Fix: Livewire component premature registration

- src/HasProfilePhoto.php
We need to typehint mutator function return to let IDE Helper package know the type of the attribute.
https://github.com/barryvdh/laravel-ide-helper/issues/1315#issuecomment-1688154721
Then PHPStan will not throw error on undefined profile_photo_url property.
> Typehint mutator profile_photo_url attribute function return

- .gitignore
- composer.json
- phpunit.xml.dist
> [4.x] Use PHPUnit 10

- composer.json
- src/Agent.php
- src/Http/Controllers/Inertia/UserProfileController.php
- src/Http/Livewire/LogoutOtherBrowserSessionsForm.php
- tests/AgentTest.php
* Port `Jenssegers\Agent\Agent` to `Laravel\Jetstream\Agent`
- Without `isRobot()` detection
> [4.x] Replace `jenssegers/agent` and use latest `mobiledetect/mobiledetectlib`

- src/Http/Livewire/DeleteTeamForm.php
Fix invalid return type.
The deleteTeam() method currently has `void` set as return type. It redirects...
This changes the return type to `\Illuminate\Http\Response | \Illuminate\Http\RedirectResponse | \Livewire\Features\SupportRedirects\Redirector `
> deleteTeam() return type

- composer.json
- src/JetstreamServiceProvider.php
Like Livewire, Inertia needs to update the password hash in the session when it is updated by the Fortify service.
> Set password in session on update for inertia

- src/Agent.php
- tests/AgentTest.php
Browser Sessions are currently showing '1-1'  when they should be displaying 'Platform - Browser', the image below shows reality/expected behaviour.
#1399 used the cache implemented in `mobiledetect/mobiledetectlib` which [only supports `bool` values](https://github.com/serbanghita/Mobile-Detect/blob/90416e034adbf939c436c8bbb16877d776fc239b/src/Cache/CacheItem.php#L15-L18). As multiple calls to `agent->platform()` and `agent->browser()` are made in the component the cache is engaged and produces boolean values instead of the expected strings.
This pull request replaces the `mobiledetect` cache implementation with a simple key value store on the `Agent` class.
Current tests pass as the first call to `agent->platform()` and `agent->browser()` do not hit the cache. Hopefully I will have time …
> [4.x] Fix Browser Sessions not showing platform and browser

- stubs/tests/EmailVerificationTest.php
- stubs/tests/PasswordResetTest.php
- stubs/tests/RegistrationTest.php
- stubs/tests/inertia/ApiTokenPermissionsTest.php
- stubs/tests/inertia/CreateApiTokenTest.php
- stubs/tests/inertia/DeleteAccountTest.php
- stubs/tests/inertia/DeleteApiTokenTest.php
- stubs/tests/inertia/InviteTeamMemberTest.php
- stubs/tests/inertia/TwoFactorAuthenticationSettingsTest.php
- stubs/tests/livewire/ApiTokenPermissionsTest.php
- stubs/tests/livewire/CreateApiTokenTest.php
- stubs/tests/livewire/DeleteAccountTest.php
- stubs/tests/livewire/DeleteApiTokenTest.php
- stubs/tests/livewire/InviteTeamMemberTest.php
- stubs/tests/livewire/TwoFactorAuthenticationSettingsTest.php
`$this->markTestSkipped()` is used in many PHPUnit tests to skip testing disabled features, and throws an exception to immediately end the test. However, there is also an unreachable `return` statement after every call to `markTestSkipped`. This causes static analysis tools like PHPStan that are looking for dead code to trigger on the tests until someone cleans them up. Since they are functionally irrelevant, it'd be nice to clean up the stubs and drop the `return` statements.
> [4.x] Remove Unreachable `return` in PHPUnit test stubs

- stubs/app/Actions/Fortify/UpdateUserProfileInformation.php
Just a small PHPDoc fix. I ran into this using PHPStan with rule level 5 in a project that uses Jetstream.
The `$input` parameter is typed as an `array<string, string>`, but `$input['photo']` is an `UploadedFile` and not a `string`.
> [4.x] Fix PHPDoc for `UpdateUserProfileInformation::update`

- src/Console/InstallCommand.php
In Fortify `1.20.0`, the default `home` config value changed from `RouteServiceProvider::HOME` to `/home` in preparation for Laravel 11 (https://github.com/laravel/fortify/pull/515/commits/2f84969caf226a667f064b997a06bcccfa4b5e36).
This has created an issue in fresh Jetstream installs that will now attempt to redirect to `/home` (which doesn't exist) instead of `/dashboard`.
Jetstream's `master` branch has already updated the installer to update `config/fortify.php` instead of `RouteServiceProvider.php`. This PR is just a temporary fix to ensure both are updated for the time being.
> [4.x] Fix home route

- src/Console/InstallCommand.php
This pull request wipes and re-runs database migrations on while installation Jetstream - because there is options, like --teams, where that users_table migration is replaced.
> [5.x] Re-runs database migrations on Jetstream

- src/Console/InstallCommand.php
- stubs/inertia/app/Http/Middleware/HandleInertiaRequests.php
- stubs/inertia/resources/js/app.js
- stubs/inertia/resources/js/ssr.js
[Ziggy v2 has just been released](https://github.com/tighten/ziggy/releases/tag/v2.0.0); this PR updates Jetstream accordingly. Corresponding Breeze PR: https://github.com/laravel/breeze/pull/359.
Since this change only affects Jetstream's installation process and stubs, I'm pretty sure it's not a breaking change for Jetstream itself and is safe to include in the current major version. Upgrading to Ziggy v2 may take more work for existing apps originally scaffolded with Jetstream, but that's a separate concern and these changes shouldn't affect it.
> Update to Ziggy v2

- stubs/inertia/resources/js/Components/Modal.vue
- stubs/livewire/resources/views/components/modal.blade.php
Currently, the Modal component uses a `<div>` element as the root with the Teleport feature. A modal like this does not properly trap tabs, allowing the user to tab to elements in the background which are supposed to be blocked by the modal.
Changing to use a `<dialog>` element improves accessibility by locking the tab order to the modal and prevents interaction with the background using the keyboard by taking advantage of native browser features.
This update should not affect any style or other features beyond the `<dialog>` behavior.
> [4.x] Change Inertia Modal.vue component to use a native <dialog> 

- stubs/inertia/resources/js/Components/Modal.vue
This removed `e.preventDefault()` on closing the modal in Modal.vue, which was not necessary and triggered an error message.
This resolves the error reported here: https://github.com/laravel/jetstream/pull/1431#discussion_r1504979937
> [4.x] Remove unnecessary e.preventDefault on modal close 

- src/Console/InstallCommand.php
Depends on https://github.com/laravel/framework/pull/50404, and this pull request ignores the `install:api` migration prompt because Jetstream already does that runs the migration command.
> [5.x] Fixes double migrate-prompt
