laravel/jetstream

stubs/resources/views/auth/two-factor-challenge.blade.php
Divs are not accessible, buttons should be used
=> chore: change divs to buttons

src/Console/InstallCommand.php, stubs/inertia/tailwind.config.js, stubs/livewire/tailwind.config.js, stubs/package.json
=> Configure Purgecss for Tailwind

stubs/inertia/resources/views/app.blade.php, stubs/livewire/resources/views/layouts/app.blade.php, stubs/resources/views/layouts/guest.blade.php
set a full qualified url for css file
=> set a fully qualified URL for css file

src/JetstreamServiceProvider.php
This is already done in the `mergeConfigFrom` method.
=> Do not check for config caching

stubs/livewire/resources/views/layouts/app.blade.php, stubs/resources/views/auth/login.blade.php, stubs/resources/views/auth/register.blade.php
set fully qualified url for login,register and logout
=> set fully qualified URL for login,register and logout

README.md
=> Example Inertia install command was missing ':install'

README.md
=> Simple typofix

composer.json
=> Update to Laravel Fortify 1.0

src/JetstreamServiceProvider.php
=> Revert "Add missing extension when publishing routes"

README.md, composer.json, src/Http/Controllers/Inertia/UserProfileController.php
=> Revert "Updating session function to use configured table"

src/Http/Controllers/Inertia/ApiTokenController.php
=> Missing Request

stubs/resources/views/auth/forgot-password.blade.php, stubs/resources/views/auth/reset-password.blade.php
set fully url forget and reset password action
=> set fully url forget and reset password action

stubs/livewire/resources/views/teams/team-member-manager.blade.php
Closing Bracketing missing is fixed
=> Missing Closing Parenthesis - Update team-member-manager.blade.php

.github/ISSUE_TEMPLATE/1_Bug_report.md
Will hopefully make it more clear sometimes.
=> [1.x] Require stack in bug report

.styleci.yml, stubs/webpack.mix.js
This will minimize the lines reported as changed in git or other version control systems when adding Jetstream to an existing project. [Link](https://github.com/laravel/laravel/blob/master/webpack.mix.js) for comparison.
=> [1.x] Match webpack.mix.js Formatting With Laravel/Laravel

stubs/resources/views/auth/verify-email.blade.php
=> [1.x] Remove hard coded routes and use Route() helper by name instead

README.md
Adds the same intro as the docs so the readme is in line with other 1st party repos.
=> [1.x] Add introduction

resources/views/components/confirms-password.blade.php, stubs/livewire/resources/views/profile/delete-user-form.blade.php, stubs/livewire/resources/views/profile/logout-other-browser-sessions-form.blade.php, stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
=> [1.x] Add translation support  to confirms-password.blade.php component

stubs/inertia/resources/js/Layouts/AppLayout.vue
Other IDE showing error when using v-for without :key
=> Add key of v-for teams

stubs/livewire/resources/views/layouts/app.blade.php, stubs/resources/views/layouts/guest.blade.php
Bump alpine.js to the latest release
=> [1.x] Bump Alpine.js version up to 2.7.0

stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
This pull request adds disable attribute to save button while profile picture is uploading.
=> [1.x] Disable save button while profile pic is uploading

src/HasTeams.php
Fixed a small typo in the PHPDoc.
=> PHPDoc fix

resources/views/components/welcome.blade.php, stubs/inertia/resources/js/Jetstream/Welcome.vue
This CSS class is not set anywhere and I couldn't find any reference to it in the rest of the project.
=> [1.x] Remove Unused arrow-right Class

stubs/inertia/resources/js/Layouts/AppLayout.vue, stubs/inertia/resources/js/Pages/API/ApiTokenManager.vue, stubs/inertia/resources/js/Pages/Profile/LogoutOtherBrowserSessionsForm.vue, stubs/inertia/resources/js/Pages/Profile/TwoFactorAuthenticationForm.vue, stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
It's recommended to provide a `:key` with `v-for` whenever possible:
> To give Vue a hint so that it can track each node’s identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item.
- https://vuejs.org/v2/guide/list.html#Maintaining-State
- https://vuejs.org/v2/api/#key
=> [1.x] Provide a unique key attribute

stubs/inertia/resources/js/Pages/Profile/DeleteUserForm.vue
=> Remove unused import

stubs/inertia/resources/js/Layouts/AppLayout.vue
=> Remove unused property

src/Events/AddingTeam.php, src/Events/InvitingTeamMember.php, stubs/app/Actions/Jetstream/AddTeamMember.php, stubs/app/Actions/Jetstream/CreateTeam.php, stubs/app/Actions/Jetstream/InviteTeamMember.php
- AddingTeam
- AddingTeamMember
- InvitingTeamMember
=> [2.x] Dispatching events before creating teams, adding members, and inviting members.

stubs/inertia/resources/js/Pages/Profile/DeleteUserForm.vue
=> [1.x] Update DeleteUserForm.vue

config/jetstream.php, routes/inertia.php, src/Features.php, src/Http/Middleware/ShareInertiaData.php, src/Jetstream.php, stubs/inertia/resources/js/Pages/Profile/Show.vue, stubs/livewire/resources/views/profile/show.blade.php
I'm building an app that shouldn't even allow users to delete their accounts.
I thought it would be useful to add it as a feature.
=> [2.x] Add account deletion feature

stubs/inertia/resources/js/Pages/Profile/Show.vue
Fixes https://github.com/laravel/jetstream/issues/445
=> [1.x] Fix feature toggles in Inertia

src/Http/Middleware/ShareInertiaData.php, stubs/inertia/resources/js/Pages/Profile/Show.vue, stubs/livewire/resources/views/profile/show.blade.php
Renamed the permissions to more sensible ones and actually provide them to Inertia as well. Not sure what went wrong there for me. Think I must have incorrectly compiled assets or something when I tested it.
=> [1.x] Provide permissions to Inertia

routes/inertia.php, routes/livewire.php, src/Console/InstallCommand.php, src/Http/Controllers/Inertia/PrivacyPolicyController.php, src/Http/Controllers/Inertia/TermsOfServiceController.php, src/Http/Controllers/Livewire/PrivacyPolicyController.php, src/Http/Controllers/Livewire/TermsOfServiceController.php, stubs/inertia/resources/js/Layouts/GuestLayout.vue, stubs/inertia/resources/js/Pages/Auth/Register.vue, stubs/inertia/resources/js/Pages/Policy.vue, stubs/inertia/resources/js/Pages/Terms.vue, stubs/resources/views/auth/register.blade.php
- Guest layout component in Vue
- route() on register page
- Separate Controllers for Livewire and Inertia to show correct view/inertia page.
- policy controller using policy view rather than terms view.
=> [2.x] Terms - inertia pages

database/factories/TeamFactory.php, database/factories/UserFactory.php, src/Console/InstallCommand.php, stubs/app/Models/Team.php
Implements #309 
UserFactory 
- also creates a personal team
- overwrites original laravel UserFactory
TeamFactory
- creates a personal_team as default
Only installs when --teams option is used.
=> [2.x] TeamFactory

database/migrations/2020_05_21_100000_create_teams_table.php, database/migrations/2020_05_21_200000_create_team_user_table.php, database/migrations/2020_05_21_300000_create_team_invitations_table.php
=> [2.x] Use dropIfExists instead of drop

stubs/resources/views/auth/register.blade.php
=> [2.x] Fix checkbox on register

.github/PULL_REQUEST_TEMPLATE.md
To make sure people are aware of this.
=> [1.x] Clarify updating of both stacks in PR template

stubs/resources/views/auth/two-factor-challenge.blade.php
Fixes https://github.com/laravel/jetstream/issues/525
=> [1.x] Use named route for two-factor

src/Actions/UpdateTeamMemberRole.php, src/Console/InstallCommand.php, src/Events/TeamEvent.php, src/HasTeams.php, src/Http/Controllers/Inertia/CurrentUserController.php, src/Http/Controllers/Inertia/OtherBrowserSessionsController.php, src/Http/Livewire/ApiTokenManager.php, src/Http/Livewire/CreateTeamForm.php, src/Http/Livewire/TeamMemberManager.php, src/Jetstream.php, src/Mail/TeamInvitation.php, src/Team.php, src/TeamInvitation.php, stubs/app/Models/TeamInvitation.php
Some methods don't have return type (or it's invalid).
Also, added missing parameter names and fixed parameter types.
=> [2.x] Update phpdoc

src/Http/Controllers/Inertia/CurrentUserController.php
`Inertia::location()` does the same thing, and it makes code easier to read:
https://github.com/inertiajs/inertia-laravel/blob/master/src/ResponseFactory.php#L78
=> [2.x] Use Inertia::location()

src/Console/InstallCommand.php, stubs/inertia/resources/js/Pages/Profile/TwoFactorAuthenticationForm.vue, stubs/inertia/resources/js/Pages/Profile/UpdateProfileInformationForm.vue, stubs/inertia/resources/js/Pages/Teams/TeamMemberManager.vue
This PR upgrades Inertia to the latest version, in which a recent signature change for `Inertia.delete` has been reverted.
- https://github.com/inertiajs/inertia/releases/tag/v0.8.2
- https://github.com/inertiajs/inertia/releases/tag/inertia-vue%40v0.5.4
=> [2.x] Minor Inertia upgrade

src/Console/InstallCommand.php, stubs/inertia/webpack.mix.js
=> Laravel mix 6 support

stubs/livewire/resources/views/navigation-menu.blade.php
=> Add @can check to mobile menu

src/Console/InstallCommand.php, stubs/webpack.mix.js
=> [1.x] Update to mix6

stubs/livewire/resources/views/teams/team-member-manager.blade.php
=> [2.x] Make cancel link translatable

stubs/inertia/resources/js/Pages/Welcome.vue, stubs/inertia/routes/web.php
There is a small design bug.
This PR will fix that problem.
=> [2.x] Make a similar footer section on welcome page

stubs/inertia/resources/js/Pages/API/Index.vue, stubs/inertia/resources/js/Pages/Teams/CreateTeamForm.vue, stubs/inertia/resources/js/Pages/Teams/DeleteTeamForm.vue
Some components are imported in inertia components but are not used.
This removes imports without any impact on the functionnalities.
=> [2.x] Remove unused Vue components

resources/views/components/banner.blade.php
There is a small design bug.
When you open you website (or refresh) it jumps a little bit as you can see on this gif.
This PR will fix that problem.
=> [2.x] Banner should be hidden in default

src/Http/Livewire/ApiTokenManager.php, stubs/livewire/resources/views/api/api-token-manager.blade.php
Resubmit of #587, apologies for the wrong target branch.
=> [2.x] Automatically select API token when it's created

UPGRADE.md
Fix links on UPGRADE.md:
- Livewire Stack Upgrade Guide
- Inertia Stack Upgrade Guide
=> [2.x] Update UPGRADE.md

src/Mail/TeamInvitation.php
=> [2.x] Make the subject of the team invitation email translatable

stubs/livewire/resources/views/auth/confirm-password.blade.php
=> [2.x] Make text translatable in confirm-password livewire view

src/Http/Livewire/TeamMemberManager.php
Fixes https://github.com/laravel/jetstream/issues/649
=> [2.x] Use custom team member model

src/Http/Controllers/Inertia/OtherBrowserSessionsController.php, src/Http/Livewire/LogoutOtherBrowserSessionsForm.php, stubs/inertia/resources/js/Layouts/AppLayout.vue, stubs/inertia/resources/js/Pages/Auth/Login.vue, stubs/inertia/resources/js/Pages/Auth/TwoFactorChallenge.vue, stubs/inertia/resources/js/Pages/Auth/VerifyEmail.vue, stubs/inertia/resources/js/Pages/Profile/LogoutOtherBrowserSessionsForm.vue, stubs/inertia/resources/js/Pages/Welcome.vue, stubs/livewire/resources/views/auth/login.blade.php, stubs/livewire/resources/views/auth/two-factor-challenge.blade.php, stubs/livewire/resources/views/auth/verify-email.blade.php, stubs/livewire/resources/views/navigation-menu.blade.php, stubs/livewire/resources/views/profile/logout-other-browser-sessions-form.blade.php
http://notaverb.com/logout
http://notaverb.com/login
See also: laravel/laravel#5536 and laravel/breeze#41
I only changed UI strings or code comments... I do not think it's worth changing methods or JS functions or filenames.
=> Change "Logout" text to "Log out" and "Login" to "Log in"

resources/views/components/danger-button.blade.php, resources/views/components/secondary-button.blade.php, stubs/inertia/resources/js/Jetstream/Button.vue, stubs/inertia/resources/js/Jetstream/DangerButton.vue, stubs/inertia/resources/js/Jetstream/SecondaryButton.vue
Add disabled attribute  in `danger-button.blade.php` and `secondary-button.blade.php` the same way that int the `button.blade.php`
=> [2.x] Button Disabled opacity-25

src/Http/Middleware/ShareInertiaData.php
=> [2.x] Revert "Reduce amount of queries for Teams feature"

stubs/tests/EmailVerificationTest.php
This PR will fix the test case in EmailVerificationTest when the emailVerification feature is enabled the team feature is enabled.
=> [2.x] - Fixed the test that's failing in EmailVerificationTest

src/Console/InstallCommand.php
Update NPM dependencies:
@tailwindcss/forms: ^0.2.1 -> ^0.3.1
@tailwindcss/typography: ^0.3.0 -> ^0.4.0
postcss-import: ^12.0.1 -> ^14.0.1
=> Update NPM dependencies

stubs/inertia/resources/js/Layouts/AppLayout.vue
=> #fixed Added canCreateTeams validation in responsive-nav-link of AppLayout #784

src/Console/InstallCommand.php
Updated tailwindcss to the latest version.
=> Update Tailwindcss to latest version

resources/views/components/dropdown.blade.php, stubs/inertia/resources/js/Jetstream/Dropdown.vue
=> Revert "Update dropdown.blade.php"

stubs/inertia/resources/js/Pages/Welcome.vue
- redirect to `dashboard` by route name.
=> redirect by route name

src/Http/Livewire/TeamMemberManager.php, stubs/app/Providers/JetstreamWithTeamsServiceProvider.php
Based feedback from https://github.com/laravel/jetstream/pull/836#issuecomment-884815468
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
=> Prepare translated roles on Livewire using `jsonSerialize()`, this make it work similarily to Inertia.

resources/views/components/action-section.blade.php
Like form-section, merge action-section component's attributes.
=> feat(components): merge action-section attributes

src/Http/Controllers/TeamInvitationController.php
=> Revert "Use custom TeamInvitation model in TeamInvitationController"

stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
Fixed a content reflow issue on slower connection in Update Profile Information Form. This issue only happens in Livewire version.
=> Fixed a content reflow issue on slower connection in update profile info form.

.github/workflows/tests.yml, composer.json
Depends on inertiajs/inertia-laravel.
=> [1.x] Laravel 9 support

.github/workflows/tests.yml, composer.json
Depends on inertiajs/inertia-laravel.
=> [2.x] Laravel 9 support

src/Console/InstallCommand.php
=> Bump inertia

src/HasProfilePhoto.php
Resend https://github.com/laravel/jetstream/pull/959 for 1.x
I saw that 1.x will also get Laravel 9 Support.
Therefor I send the PR again against the 1.x branch to make the upgrade to Laravel 9 easier for People who are still using 1.x.
=> [1.x] Add Check before deleting profile photo

stubs/app/Actions/Fortify/CreateNewUser.php
hi,
just a minor tweak for a more user friendly validation message
=> Priorize 'accepted' validation rule for terms checkbox

src/ConfirmsPasswords.php
=> Remove return in ensurePasswordIsConfirmed

stubs/app/Actions/Fortify/CreateNewUserWithTeams.php
=> Prioritize 'accepted' validation rule for terms checkbox in CreateNewUserWithTeams.php

resources/views/components/switchable-team.blade.php
Fix parse error caused by alpine shorthand on dynamic-component
=> [2.x] Fix parse error caused by alpine shorthand on dynamic-component

stubs/inertia/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
Fixes small typo in https://github.com/laravel/jetstream/pull/1048
=> Fix small typo

src/Http/Middleware/ShareInertiaData.php, stubs/inertia/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue, stubs/livewire/resources/views/profile/update-profile-information-form.blade.php
This fixes some issues with email verification being disabled and the rendered link below the email field.
Fixes #1052
=> Fix disabled email verification mode

composer.json, src/Console/InstallCommand.php
This pull request improves the console output of Jetstream.
=> [2.x] Improves console output

src/Console/InstallCommand.php
Reverts laravel/jetstream#1111
=> Revert "[2.x] Validate the stack argument"

src/Http/Controllers/Inertia/TeamController.php
Allows additional data to be passed in as props to the front end. My use case would be to have different options for the groups that are being created which is dependent on what subscription plan they are on or something similar. Thanks!
=> Pass additional props to the teams create view.

UPGRADE.md
=> Upgrading Jetstream in order to use team invites requires the InviteTeamMember action

composer.json, src/Console/InstallCommand.php, stubs/inertia/resources/views/app.blade.php
Depends on: https://github.com/laravel/framework/pull/44096
=> [2.x] Vite preloading

database/factories/UserFactory.php
Reverts laravel/jetstream#1168
=> Revert "Include all user table columns in the UserFactory"

src/Console/InstallCommand.php
=> [2.x] Vite 4 support

stubs/inertia/resources/js/Pages/API/Partials/ApiTokenManager.vue, stubs/livewire/resources/views/api/api-token-manager.blade.php
=> Fixed and issue causing overflow in ApiTokenManager page on mobile devices.

src/Console/InstallCommand.php, stubs/inertia/resources/js/Components/AuthenticationCardLogo.vue, stubs/inertia/resources/js/Components/Banner.vue, stubs/inertia/resources/js/Components/DropdownLink.vue, stubs/inertia/resources/js/Components/NavLink.vue, stubs/inertia/resources/js/Components/ResponsiveNavLink.vue, stubs/inertia/resources/js/Layouts/AppLayout.vue, stubs/inertia/resources/js/Pages/API/Partials/ApiTokenManager.vue, stubs/inertia/resources/js/Pages/Auth/ConfirmPassword.vue, stubs/inertia/resources/js/Pages/Auth/ForgotPassword.vue, stubs/inertia/resources/js/Pages/Auth/Login.vue, stubs/inertia/resources/js/Pages/Auth/Register.vue, stubs/inertia/resources/js/Pages/Auth/ResetPassword.vue, stubs/inertia/resources/js/Pages/Auth/TwoFactorChallenge.vue, stubs/inertia/resources/js/Pages/Auth/VerifyEmail.vue, stubs/inertia/resources/js/Pages/PrivacyPolicy.vue, stubs/inertia/resources/js/Pages/Profile/Partials/DeleteUserForm.vue, stubs/inertia/resources/js/Pages/Profile/Partials/LogoutOtherBrowserSessionsForm.vue, stubs/inertia/resources/js/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue, stubs/inertia/resources/js/Pages/Profile/Partials/UpdatePasswordForm.vue, stubs/inertia/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue, stubs/inertia/resources/js/Pages/Teams/Partials/CreateTeamForm.vue, stubs/inertia/resources/js/Pages/Teams/Partials/DeleteTeamForm.vue, stubs/inertia/resources/js/Pages/Teams/Partials/TeamMemberManager.vue, stubs/inertia/resources/js/Pages/Teams/Partials/UpdateTeamNameForm.vue, stubs/inertia/resources/js/Pages/TermsOfService.vue, stubs/inertia/resources/js/Pages/Welcome.vue, stubs/inertia/resources/js/app.js, stubs/inertia/resources/js/ssr.js
This PR updates the Inertia stack to Inertia 1.0.
TODO:
=> [2.x] Inertia v1

stubs/inertia/resources/js/Layouts/AppLayout.vue, stubs/livewire/resources/views/navigation-menu.blade.php
Reverts laravel/jetstream#1225
=> Revert "Update nav menu dark text to be consistent with nav link"

stubs/app/Models/Team.php, stubs/app/Models/TeamInvitation.php, stubs/app/Models/UserWithTeams.php
=> Type Error in PHPdoc

.github/workflows/tests.yml, src/Console/InstallCommand.php
Similar to https://github.com/laravel/breeze/pull/251, this pull request allows the installation of Pest in Laravel 10.
=> [2.x] Fixes Laravel 10 `--pest` installation

stubs/inertia/resources/js/Components/Welcome.vue, stubs/inertia/resources/js/Pages/Welcome.vue, stubs/inertia/resources/views/app.blade.php, stubs/inertia/tailwind.config.js, stubs/livewire/resources/views/components/welcome.blade.php, stubs/livewire/resources/views/layouts/app.blade.php, stubs/livewire/resources/views/layouts/guest.blade.php, stubs/livewire/tailwind.config.js
This PR updates the Vue version of the welcome page to match the Laravel 10 skeleton (see https://github.com/laravel/laravel/pull/6093).
It also updates the default font for the entire application and makes a few minor visual tweaks to welcome component you see after logging in:
**Light mode**
**Dark mode**
=> [3.x] New welcome

UPGRADE.md
This PR adds an upgrade guide from Jetstream 2.x to Jetstream 3.x.
=> [3.x] Upgrade guide

src/JetstreamServiceProvider.php
=> [3.x] Removed loadViewsFrom

.gitattributes, .github/workflows/static-analysis.yml, composer.json, phpstan.neon.dist, src/JetstreamServiceProvider.php, tests/OrchestraTestCase.php
This pull request adds type checking to this repository.
=> [3.x] Adds type checking

stubs/inertia/resources/js/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue
use route helper in TwoFactorAuthenticationForm.vue
=> Use route helper in two factor authentication form

src/Http/Livewire/UpdateProfileInformationForm.php
Reverts laravel/jetstream#1309
=> Revert "Ensure email is included in state"

stubs/inertia/postcss.config.js, stubs/inertia/tailwind.config.js, stubs/livewire/postcss.config.js, stubs/livewire/tailwind.config.js
We did a release of Jetstream between me opening and us merging, and I missed changing the base for https://github.com/laravel/jetstream/pull/1242
Fixes #1314
=> [3.x] Migrate to modules

src/Console/InstallCommand.php, stubs/app/Models/User.php
Just 2 little things Laravel Pint always fixes
=> [3.x] Laravel Pint fixes

stubs/inertia/resources/js/Layouts/AppLayout.vue
This PR removes a redundant v-if statement from the menu in the Inertia stack.
=> Remove redundant v-if from menu

UPGRADE.md
This pull request is a work in progress, and it contains the upgrade guide for Jetstream `4.x`.
=> [4.x] Upgrade guide

stubs/app/Actions/Jetstream/DeleteUserWithTeams.php
This pull request uses property promotion on the `DeleteUser` implemention stub.
=> [5.x] Uses property promotion on `DeleteUser`

stubs/livewire/resources/views/auth/forgot-password.blade.php, stubs/livewire/resources/views/auth/login.blade.php
This will update the login and forgot password Livewire views to use the recently added `@session` Blade directive to check if the session contains a `status` message.
=> [5.x] Use `@session` Blade Directive

stubs/inertia/resources/js/Pages/Welcome.vue
Pairs with https://github.com/laravel/breeze/pull/362
=> Implement new welcome page design

UPGRADE.md
This pull request adds the upgrade guide of Jetstream 5.x
=> [5.x] Adds upgrade guide
